FROM node:20-alpine AS build

WORKDIR /app

COPY backend/package*.json ./
RUN npm ci

COPY backend ./
RUN npm run prisma:generate && npm run build

FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache curl

ENV NODE_ENV=production

COPY --from=build /app/package*.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/dist ./dist
COPY updates /updates

EXPOSE 3333

CMD ["node", "dist/server.js"]
