
FROM node:20-alpine AS build

WORKDIR /usr/src/app

ARG VITE_GOOGLE_CLIENT_ID
ARG VITE_GOOGLE_ALLOWED_ORIGINS
ARG VITE_API_URL

ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
ENV VITE_GOOGLE_ALLOWED_ORIGINS=$VITE_GOOGLE_ALLOWED_ORIGINS
ENV VITE_API_URL=$VITE_API_URL

COPY frontend/package*.json ./
RUN npm ci

COPY frontend .
COPY backend/src/main/resources/static/version.txt ./.g3-version

RUN npm run build

FROM nginx:1.27-alpine

# Needed for entrypoint templating and healthcheck
RUN apk add --no-cache python3 wget gettext

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf


COPY --from=build /usr/src/app/dist/ /usr/share/nginx/html/

COPY frontend/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
