import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { cipaService } from "@/services/cipa.service";

const tipos = [{ id: "EDITAL", nome: "Edital" }, { id: "COMUNICADO", nome: "Comunicado" }, { id: "RELACAO_CANDIDATOS", nome: "Relação de candidatos" }, { id: "ZERESIMA", nome: "Zerésima" }, { id: "APURACAO", nome: "Relatório de apuração" }, { id: "RESULTADO_OFICIAL", nome: "Resultado oficial" }, { id: "ATA_ELEICAO", nome: "Ata de eleição" }, { id: "ATA_POSSE", nome: "Ata de posse" }] as const;
const relatorios = [{ id: "ELEITORES_APTOS", nome: "Eleitores aptos" }, { id: "ELEITORES_VOTARAM", nome: "Eleitores que votaram" }, { id: "ELEITORES_PENDENTES", nome: "Eleitores pendentes" }, { id: "CANDIDATOS", nome: "Candidatos" }, { id: "PARTICIPACAO", nome: "Participação" }, { id: "APURACAO", nome: "Apuração em Excel" }, { id: "RESULTADO_FINAL", nome: "Resultado em Excel" }, { id: "AUDITORIA", nome: "Auditoria" }, { id: "HISTORICO", nome: "Histórico" }] as const;
export function CipaDocumentos({ eleicaoId }: { eleicaoId: string }) {
  const [carregando, setCarregando] = useState<string>(); const [mensagem, setMensagem] = useState("");
  const documentosQuery = useQuery({ queryKey: ["cipa", "documentos", eleicaoId], queryFn: () => cipaService.listarDocumentos(eleicaoId) });
  async function gerar(tipo: (typeof tipos)[number]["id"], nome: string) { setCarregando(tipo); setMensagem(""); try { const data = await cipaService.gerarDocumento(eleicaoId, tipo); setMensagem(`${nome} gerado com sucesso: ${data.nomeArquivo}.`); } catch { setMensagem(`Não foi possível gerar ${nome.toLowerCase()}. Revise a etapa da eleição.`); } finally { setCarregando(undefined); } }
  async function baixar(id: string, nome: string) { const blob = await cipaService.baixarDocumento(eleicaoId, id); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = nome; link.click(); URL.revokeObjectURL(url); }
  async function baixarRelatorio(tipo: (typeof relatorios)[number]["id"], nome: string) { setCarregando(tipo); setMensagem(""); try { const blob = await cipaService.baixarRelatorio(eleicaoId, tipo); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `cipa-${tipo.toLowerCase()}-${eleicaoId}.csv`; link.click(); URL.revokeObjectURL(url); setMensagem(`${nome} baixado com sucesso.`); } catch { setMensagem(`Não foi possível gerar ${nome.toLowerCase()}.`); } finally { setCarregando(undefined); } }
  return <Card><CardHeader><CardTitle>Documentos e relatórios da eleição</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-[var(--g3-muted)]">Gere documentos versionados no storage oficial e relatórios compatíveis com Excel.</p><div><p className="mb-2 text-sm font-medium">Documentos oficiais</p><div className="flex flex-wrap gap-2">{tipos.map((tipo) => <Button key={tipo.id} variant="outline" size="sm" disabled={!!carregando} onClick={() => void gerar(tipo.id, tipo.nome)}>{carregando === tipo.id ? "Gerando..." : tipo.nome}</Button>)}</div></div><div><p className="mb-2 text-sm font-medium">Relatórios</p><div className="flex flex-wrap gap-2">{relatorios.map((tipo) => <Button key={tipo.id} variant="outline" size="sm" disabled={!!carregando} onClick={() => void baixarRelatorio(tipo.id, tipo.nome)}>{carregando === tipo.id ? "Baixando..." : tipo.nome}</Button>)}</div></div>{mensagem ? <p role="status" className="text-sm text-[var(--g3-muted)]">{mensagem}</p> : null}<div className="space-y-2">{documentosQuery.data?.documentos.map((documento) => <div key={documento.id} className="flex flex-wrap items-center justify-between gap-2 rounded-md border border-[var(--g3-border)] p-2 text-sm"><span>{documento.nomeArquivo} · versão {documento.versao}</span><Button size="sm" variant="ghost" onClick={() => void baixar(documento.id, documento.nomeArquivo)}>Baixar</Button></div>)}</div></CardContent></Card>;
}
