import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Download, FileText, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { imprimirHtml } from "@/lib/report-utils";
import { cipaService } from "@/services/cipa.service";

const tipos = [{ id: "EDITAL", nome: "Edital" }, { id: "COMUNICADO", nome: "Comunicado" }, { id: "RELACAO_CANDIDATOS", nome: "Relação de candidatos" }, { id: "ZERESIMA", nome: "Zerésima" }, { id: "APURACAO", nome: "Relatório de apuração" }, { id: "RESULTADO_OFICIAL", nome: "Resultado oficial" }, { id: "ATA_ELEICAO", nome: "Ata de eleição" }, { id: "ATA_POSSE", nome: "Ata de posse" }] as const;
const relatorios = [{ id: "ELEITORES_APTOS", nome: "Eleitores aptos" }, { id: "ELEITORES_VOTARAM", nome: "Eleitores que votaram" }, { id: "ELEITORES_PENDENTES", nome: "Eleitores pendentes" }, { id: "CANDIDATOS", nome: "Candidatos" }, { id: "PARTICIPACAO", nome: "Participação" }, { id: "APURACAO", nome: "Apuração em Excel" }, { id: "RESULTADO_FINAL", nome: "Resultado em Excel" }, { id: "AUDITORIA", nome: "Auditoria" }, { id: "HISTORICO", nome: "Histórico" }] as const;
function esc(v: unknown) { return String(v ?? "").replace(/[&<>"']/gu, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c] ?? c); }
function parseCsv(s: string) { return s.replace(/^\uFEFF/u, "").split(/\r?\n/u).filter(Boolean).map((l) => l.split(";").map((v) => v.replace(/^"|"$/gu, "").replaceAll('""', '"'))); }

export function CipaDocumentos({ eleicaoId }: { eleicaoId: string }) {
  const [carregando, setCarregando] = useState<string>(); const [mensagem, setMensagem] = useState("");
  const documentosQuery = useQuery({ queryKey: ["cipa", "documentos", eleicaoId], queryFn: () => cipaService.listarDocumentos(eleicaoId) });
  async function gerar(id: (typeof tipos)[number]["id"], nome: string) { setCarregando(id); setMensagem(""); try { const data = await cipaService.gerarDocumento(eleicaoId, id); await documentosQuery.refetch(); setMensagem(`${nome} gerado com sucesso: ${data.nomeArquivo}.`); } catch { setMensagem(`Não foi possível gerar ${nome.toLowerCase()}. Revise a etapa da eleição.`); } finally { setCarregando(undefined); } }
  async function baixarDocumento(id: string, nome: string) { const blob = await cipaService.baixarDocumento(eleicaoId, id); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = nome; a.click(); URL.revokeObjectURL(url); }
  async function relatorio(id: (typeof relatorios)[number]["id"], nome: string, imprimir = false) { setCarregando(`${imprimir ? "imprimir-" : ""}${id}`); setMensagem(""); try { const blob = await cipaService.baixarRelatorio(eleicaoId, id); if (!imprimir) { const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `cipa-${id.toLowerCase()}-${eleicaoId}.csv`; a.click(); URL.revokeObjectURL(url); setMensagem(`${nome} baixado com sucesso.`); } else { const rows = parseCsv(await blob.text()); const head = rows.shift() ?? []; imprimirHtml({ titulo: `Relatório — ${nome}`, tamanhoPagina: "A4", margemPagina: "12mm", paddingRaiz: "0", html: `<header class="cab"><strong>G3N — Gestão de Eleições da CIPA<small>Relatório oficial do processo eleitoral</small></strong><span>Emitido em ${esc(new Date().toLocaleString("pt-BR"))}</span></header><h1>${esc(nome)}</h1><p class="sub">Eleição CIPA · Identificador ${esc(eleicaoId)}</p><table><thead><tr>${head.map((x) => `<th>${esc(x)}</th>`).join("")}</tr></thead><tbody>${rows.map((r) => `<tr>${r.map((x) => `<td>${esc(x)}</td>`).join("")}</tr>`).join("")}</tbody></table><footer>Processo estruturado para apoiar o atendimento aos requisitos aplicáveis da NR-5. G3N · ${esc(new Date().toLocaleString("pt-BR"))}</footer>`, estilosExtras: ".cab{display:flex;justify-content:space-between;border-bottom:2px solid #087443;padding-bottom:12px;margin-bottom:18px;color:#12352a}.cab small{display:block;font-size:11px;color:#64756d;margin-top:4px}.cab span,.sub{font-size:11px;color:#64756d}h1{font-size:20px;margin:0 0 4px}table{font-size:9px}th,td{border:1px solid #d5e0da;padding:6px;text-align:left}th{background:#eaf5ee}tr:nth-child(even){background:#f8fbf9}footer{border-top:1px solid #d5e0da;margin-top:18px;padding-top:8px;font-size:9px;color:#64756d}thead{display:table-header-group}tr{break-inside:avoid}" }); } } catch { setMensagem(`Não foi possível gerar ${nome.toLowerCase()}.`); } finally { setCarregando(undefined); } }
  return <Card><CardHeader><CardTitle>Documentos e relatórios da eleição</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-[var(--g3-muted)]">Documentos oficiais versionados no storage institucional. Relatórios com exportação para Excel e impressão no padrão do G3N.</p><section><p className="mb-2 flex items-center gap-2 text-sm font-medium"><FileText className="h-4 w-4" />Documentos oficiais</p><div className="flex flex-wrap gap-2">{tipos.map((t) => <Button key={t.id} variant="outline" size="sm" disabled={!!carregando} onClick={() => void gerar(t.id, t.nome)}>{carregando === t.id ? "Gerando..." : t.nome}</Button>)}</div></section><section><p className="mb-2 flex items-center gap-2 text-sm font-medium"><FileText className="h-4 w-4" />Relatórios</p><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{relatorios.map((t) => <div key={t.id} className="flex items-center justify-between gap-2 rounded-md border border-[var(--g3-border)] p-2"><span className="text-sm">{t.nome}</span><span className="flex gap-1"><Button aria-label={`Imprimir ${t.nome}`} title="Imprimir relatório" size="sm" className="h-8 w-8 p-0" variant="ghost" disabled={!!carregando} onClick={() => void relatorio(t.id, t.nome, true)}><Printer className="h-4 w-4" /></Button><Button aria-label={`Baixar ${t.nome}`} title="Baixar Excel" size="sm" className="h-8 w-8 p-0" variant="ghost" disabled={!!carregando} onClick={() => void relatorio(t.id, t.nome)}><Download className="h-4 w-4" /></Button></span></div>)}</div></section>{mensagem ? <p role="status" className="text-sm text-[var(--g3-muted)]">{mensagem}</p> : null}<div className="space-y-2">{documentosQuery.data?.documentos.map((d) => <div key={d.id} className="flex flex-wrap items-center justify-between gap-2 rounded-md border border-[var(--g3-border)] p-2 text-sm"><span>{d.nomeArquivo} · versão {d.versao}</span><Button size="sm" variant="ghost" onClick={() => void baixarDocumento(d.id, d.nomeArquivo)}>Baixar PDF</Button></div>)}</div></CardContent></Card>;
}
