import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { cipaService } from "@/services/cipa.service";

export function CipaGestaoOperacional({ eleicaoId }: { eleicaoId: string }) {
  const queryClient = useQueryClient(); const candidaturas = useQuery({ queryKey: ["cipa", "candidaturas", eleicaoId], queryFn: () => cipaService.listarCandidaturas(eleicaoId) }); const comissao = useQuery({ queryKey: ["cipa", "comissao", eleicaoId], queryFn: () => cipaService.listarComissao(eleicaoId) }); const [nome, setNome] = useState(""); const [funcao, setFuncao] = useState(""); const [mensagem, setMensagem] = useState("");
  const atualizar = useMutation({ mutationFn: ({ id, status }: { id: string; status: "APROVADA" | "REPROVADA" | "CORRECAO_SOLICITADA" }) => cipaService.alterarStatusCandidatura(eleicaoId, id, status), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["cipa", "candidaturas", eleicaoId] }); void queryClient.invalidateQueries({ queryKey: ["cipa", "dashboard", eleicaoId] }); } });
  const adicionar = useMutation({ mutationFn: () => cipaService.adicionarComissao(eleicaoId, { nome, funcao }), onSuccess: () => { setNome(""); setFuncao(""); setMensagem("Membro adicionado à comissão eleitoral."); void queryClient.invalidateQueries({ queryKey: ["cipa", "comissao", eleicaoId] }); } });
  const remover = useMutation({ mutationFn: (id: string) => cipaService.removerComissao(eleicaoId, id), onSuccess: () => void queryClient.invalidateQueries({ queryKey: ["cipa", "comissao", eleicaoId] }) });
  return <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Análise de candidaturas</CardTitle></CardHeader><CardContent className="space-y-2">{candidaturas.isLoading ? <p className="text-sm text-[var(--g3-muted)]">Carregando candidaturas...</p> : !candidaturas.data?.candidaturas.length ? <p className="text-sm text-[var(--g3-muted)]">Nenhuma candidatura cadastrada.</p> : candidaturas.data.candidaturas.map((item) => <div key={item.id} className="rounded-md border border-[var(--g3-border)] p-3"><div className="flex items-start justify-between gap-2"><div><p className="font-medium">{item.numero} — {item.nomePublico}</p><p className="text-xs text-[var(--g3-muted)]">{item.protocolo} · {item.status.replaceAll("_", " ")}</p></div>{item.status === "EM_ANALISE" ? <div className="flex gap-1"><Button size="sm" onClick={() => atualizar.mutate({ id: item.id, status: "APROVADA" })}>Aprovar</Button><Button size="sm" variant="outline" onClick={() => atualizar.mutate({ id: item.id, status: "CORRECAO_SOLICITADA" })}>Pedir correção</Button><Button size="sm" variant="danger" onClick={() => atualizar.mutate({ id: item.id, status: "REPROVADA" })}>Reprovar</Button></div> : null}</div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Comissão eleitoral</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 sm:grid-cols-2"><div><Label htmlFor="cipa-membro-nome">Nome</Label><Input id="cipa-membro-nome" value={nome} onChange={(event) => setNome(event.target.value)} /></div><div><Label htmlFor="cipa-membro-funcao">Função</Label><Input id="cipa-membro-funcao" value={funcao} onChange={(event) => setFuncao(event.target.value)} /></div></div><Button disabled={!nome.trim() || !funcao.trim() || adicionar.isPending} onClick={() => void adicionar.mutateAsync()}>{adicionar.isPending ? "Adicionando..." : "Adicionar membro"}</Button>{mensagem ? <p role="status" className="text-sm text-[var(--g3-muted)]">{mensagem}</p> : null}<div className="space-y-2">{comissao.data?.membros.map((item) => <div key={item.id} className="flex items-center justify-between rounded-md border border-[var(--g3-border)] p-2 text-sm"><span>{item.nome} · {item.funcao}</span><Button size="sm" variant="ghost" onClick={() => void remover.mutateAsync(item.id)}>Remover</Button></div>)}</div></CardContent></Card></div>;
}
