import { useState } from "react";
import { CheckCircle2, ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { useCriarEleicaoCipa } from "@/features/cipa/use-cipa";
import { useUnidadesAssistenciais } from "@/features/unidades-assistenciais/use-unidades-assistenciais";

const etapas = ["Identificação", "Cronograma", "Eleitores", "Candidatos", "Regras", "Segurança", "Publicação"];
const isoHoje = new Date().toISOString().slice(0, 10);
const adicionarDias = (dias: number) => { const data = new Date(`${isoHoje}T12:00:00`); data.setDate(data.getDate() + dias); return data.toISOString().slice(0, 10); };

export function CipaWizardEleicao({ onConcluida }: { onConcluida: () => void }) {
  const unidadesQuery = useUnidadesAssistenciais({});
  const criarMutation = useCriarEleicaoCipa();
  const [etapa, setEtapa] = useState(0);
  const [form, setForm] = useState({ nome: "Eleição da CIPA", gestao: "2026/2027", unidadeId: "", descricao: "", observacoes: "", inscricoesInicio: isoHoje, inscricoesFim: adicionarDias(15), divulgacaoCandidatosEm: adicionarDias(16), votacaoInicio: adicionarDias(17), votacaoFim: adicionarDias(18), apuracaoEm: adicionarDias(18), publicacaoPrevistaEm: adicionarDias(19), posseEm: adicionarDias(20), titulares: 1, suplentes: 1, votosPorEleitor: 1, permiteVotoBranco: true, permiteVotoNulo: true, permiteVotacaoCelular: true, permiteVotacaoPresencial: false, regraDesempate: "TEMPO_SERVICO_ESTABELECIMENTO" as const });
  const atualizar = (campo: string, valor: string | number | boolean) => setForm((atual) => ({ ...atual, [campo]: valor }));
  const podeAvancar = etapa === 0 ? Boolean(form.nome.trim() && form.gestao.trim() && form.unidadeId) : etapa === 1 ? Boolean(form.inscricoesInicio && form.inscricoesFim && form.votacaoInicio && form.votacaoFim) : true;
  async function concluir() { if (!podeAvancar) return; await criarMutation.mutateAsync(form); onConcluida(); }
  return <Card><CardHeader><CardTitle>Nova eleição da CIPA</CardTitle><div className="mt-3 grid grid-cols-7 gap-1" aria-label="Etapas da criação">{etapas.map((nome, indice) => <button key={nome} type="button" className={`rounded px-1 py-2 text-[10px] font-medium sm:text-xs ${indice === etapa ? "bg-[var(--g3-active)] text-white" : indice < etapa ? "bg-[var(--g3-primary-soft)] text-[var(--g3-active)]" : "bg-[var(--g3-card-soft)] text-[var(--g3-muted)]"}`} onClick={() => indice <= etapa && setEtapa(indice)} aria-current={indice === etapa ? "step" : undefined}>{indice < etapa ? "✓ " : ""}{nome}</button>)}</div></CardHeader><CardContent className="space-y-4">
    {etapa === 0 ? <div className="grid gap-4 md:grid-cols-2"><div><Label htmlFor="cipa-wizard-nome">Nome da eleição</Label><Input id="cipa-wizard-nome" value={form.nome} onChange={(event) => atualizar("nome", event.target.value)} /></div><div><Label htmlFor="cipa-wizard-gestao">Gestão</Label><Input id="cipa-wizard-gestao" value={form.gestao} onChange={(event) => atualizar("gestao", event.target.value)} /></div><div><Label htmlFor="cipa-wizard-unidade">Estabelecimento</Label><Select id="cipa-wizard-unidade" value={form.unidadeId} onChange={(event) => atualizar("unidadeId", event.target.value)}><option value="">Selecione o estabelecimento</option>{(unidadesQuery.data?.unidades ?? []).map((unidade) => <option key={unidade.id_unidade} value={unidade.id_unidade}>{unidade.nome_fantasia}</option>)}</Select></div><div><Label htmlFor="cipa-wizard-descricao">Descrição</Label><Input id="cipa-wizard-descricao" value={form.descricao} onChange={(event) => atualizar("descricao", event.target.value)} /></div><div className="md:col-span-2"><Label htmlFor="cipa-wizard-observacoes">Observações</Label><textarea id="cipa-wizard-observacoes" className="min-h-20 w-full rounded-md border border-[var(--g3-border)] p-3 text-sm" value={form.observacoes} onChange={(event) => atualizar("observacoes", event.target.value)} /></div></div> : null}
    {etapa === 1 ? <div className="grid gap-4 md:grid-cols-2"><p className="md:col-span-2 text-sm text-[var(--g3-muted)]">O período de inscrições deve respeitar o mínimo configurado. As datas são validadas novamente no servidor.</p>{([["inscricoesInicio", "Início das inscrições"], ["inscricoesFim", "Fim das inscrições"], ["divulgacaoCandidatosEm", "Divulgação dos candidatos"], ["votacaoInicio", "Início da votação"], ["votacaoFim", "Fim da votação"], ["apuracaoEm", "Data da apuração"], ["publicacaoPrevistaEm", "Publicação prevista"], ["posseEm", "Data de posse"]] as const).map(([campo, label]) => <div key={campo}><Label htmlFor={`cipa-wizard-${campo}`}>{label}</Label><Input id={`cipa-wizard-${campo}`} type="date" value={form[campo]} onChange={(event) => atualizar(campo, event.target.value)} /></div>)}</div> : null}
    {etapa === 2 ? <div className="space-y-3"><p className="text-sm text-[var(--g3-muted)]">Depois de criar a eleição, você poderá selecionar colaboradores do cadastro oficial, importar planilha, validar CPF e revisar duplicidades.</p><div className="rounded-lg bg-[var(--g3-primary-soft)] p-4 text-sm"><strong>Próximo passo após salvar:</strong> inclua os eleitores na aba operacional da eleição. Nenhum eleitor fictício será criado automaticamente.</div></div> : null}
    {etapa === 3 ? <div className="space-y-3"><p className="text-sm text-[var(--g3-muted)]">As candidaturas poderão ser cadastradas pelo portal do colaborador ou pela comissão eleitoral, com análise, aprovação e protocolo.</p><div className="rounded-lg bg-[var(--g3-primary-soft)] p-4 text-sm"><strong>Próximo passo após salvar:</strong> abra as inscrições e acompanhe as candidaturas no painel.</div></div> : null}
    {etapa === 4 ? <div className="grid gap-4 md:grid-cols-2"><div><Label htmlFor="cipa-wizard-titulares">Quantidade de titulares</Label><Input id="cipa-wizard-titulares" type="number" min={1} value={form.titulares} onChange={(event) => atualizar("titulares", Number(event.target.value))} /></div><div><Label htmlFor="cipa-wizard-suplentes">Quantidade de suplentes</Label><Input id="cipa-wizard-suplentes" type="number" min={0} value={form.suplentes} onChange={(event) => atualizar("suplentes", Number(event.target.value))} /></div><div><Label htmlFor="cipa-wizard-votos">Votos permitidos por eleitor</Label><Input id="cipa-wizard-votos" type="number" min={1} value={form.votosPorEleitor} onChange={(event) => atualizar("votosPorEleitor", Number(event.target.value))} /></div><div><Label htmlFor="cipa-wizard-desempate">Critério de desempate</Label><Select id="cipa-wizard-desempate" value={form.regraDesempate} onChange={(event) => atualizar("regraDesempate", event.target.value)}><option value="TEMPO_SERVICO_ESTABELECIMENTO">Tempo de serviço no estabelecimento</option><option value="SORTEIO_AUDITADO">Sorteio auditado</option><option value="REGRA_CUSTOMIZADA">Regra customizada</option></Select></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.permiteVotoBranco} onChange={(event) => atualizar("permiteVotoBranco", event.target.checked)} />Permitir voto em branco</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.permiteVotoNulo} onChange={(event) => atualizar("permiteVotoNulo", event.target.checked)} />Permitir voto nulo</label></div> : null}
    {etapa === 5 ? <div className="space-y-3"><div className="rounded-lg border border-[var(--g3-border)] p-4"><p className="font-medium">Proteções aplicadas por padrão</p><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-[var(--g3-muted)]"><li>Autenticação validada no backend.</li><li>Uma participação por eleitor com restrição única.</li><li>Voto separado do registro de participação.</li><li>Auditoria administrativa e isolamento por tenant.</li></ul></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.permiteVotacaoCelular} onChange={(event) => atualizar("permiteVotacaoCelular", event.target.checked)} />Permitir votação pelo celular</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.permiteVotacaoPresencial} onChange={(event) => atualizar("permiteVotacaoPresencial", event.target.checked)} />Habilitar votação presencial (quando disponível)</label></div> : null}
    {etapa === 6 ? <div className="space-y-3"><p className="text-sm text-[var(--g3-muted)]">A eleição será salva como configuração inicial. Antes de publicar, confira o checklist no painel:</p>{["Eleitores cadastrados", "Candidatos aprovados", "Comissão eleitoral definida", "Cronograma válido", "Regras configuradas", "Documentos gerados", "Urna configurada", "Teste realizado"].map((item) => <div key={item} className="flex items-center gap-2 rounded-lg bg-[var(--g3-card-soft)] p-3 text-sm"><CheckCircle2 className="h-4 w-4 text-[var(--g3-muted)]" aria-hidden="true" />{item}</div>)}<p className="text-xs text-[var(--g3-muted)]">A publicação continuará bloqueada pelo checklist do servidor até os requisitos obrigatórios serem atendidos.</p></div> : null}
    {criarMutation.isError ? <p role="alert" className="text-sm text-red-700">Não foi possível salvar a eleição. Revise o cronograma e tente novamente.</p> : null}<div className="flex flex-wrap justify-between gap-2"><Button variant="outline" onClick={() => etapa === 0 ? onConcluida() : setEtapa((atual) => atual - 1)}><ChevronLeft className="mr-1 h-4 w-4" />{etapa === 0 ? "Cancelar" : "Voltar"}</Button>{etapa < etapas.length - 1 ? <Button onClick={() => { if (podeAvancar) setEtapa((atual) => atual + 1); }} disabled={!podeAvancar}>Próxima etapa<ChevronRight className="ml-1 h-4 w-4" /></Button> : <Button onClick={() => void concluir()} disabled={criarMutation.isPending || !podeAvancar}>{criarMutation.isPending ? "Salvando..." : "Salvar eleição"}</Button>}</div>
  </CardContent></Card>;
}
