import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { cipaService } from "@/services/cipa.service";

type Props = { eleicaoId: string; status: string; onPublicado: () => void };

export function CipaResultadoEleicao({ eleicaoId, status, onPublicado }: Props) {
  const queryClient = useQueryClient();
  const resultado = useQuery({ queryKey: ["cipa", "apuracao", eleicaoId], queryFn: () => cipaService.buscarApuracao(eleicaoId), enabled: ["APURACAO", "RESULTADO_PUBLICADO", "ENCERRADA"].includes(status) });
  const candidaturas = useQuery({ queryKey: ["cipa", "candidaturas", eleicaoId], queryFn: () => cipaService.listarCandidaturas(eleicaoId), enabled: status === "VOTACAO_ENCERRADA" });
  const [criterio, setCriterio] = useState<"TEMPO_SERVICO_ESTABELECIMENTO" | "SORTEIO_AUDITADO" | "REGRA_CUSTOMIZADA">("SORTEIO_AUDITADO");
  const [justificativa, setJustificativa] = useState(""); const [mensagem, setMensagem] = useState("");
  const desempate = useMutation({ mutationFn: () => cipaService.registrarDesempate(eleicaoId, (candidaturas.data?.candidaturas ?? []).filter((item) => item.status === "APROVADA").map((item, index) => ({ candidaturaId: item.id, ordem: index + 1, criterio, justificativa }))), onSuccess: () => setMensagem("Desempate registrado na trilha de auditoria.") });
  const publicar = useMutation({ mutationFn: () => cipaService.publicarResultado(eleicaoId), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["cipa", "apuracao", eleicaoId] }); onPublicado(); } });
  if (status === "VOTACAO_ENCERRADA") return <Card><CardHeader><CardTitle>Desempate auditado</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-[var(--g3-muted)]">Se houver empate sem critério automático suficiente, registre a ordem definida pela comissão antes da apuração.</p><div><label htmlFor="cipa-criterio-desempate" className="text-sm font-medium">Critério</label><select id="cipa-criterio-desempate" className="mt-1 h-9 w-full rounded-md border border-[var(--g3-border)] bg-white px-2 text-sm" value={criterio} onChange={(event) => setCriterio(event.target.value as typeof criterio)}><option value="SORTEIO_AUDITADO">Sorteio auditado</option><option value="TEMPO_SERVICO_ESTABELECIMENTO">Tempo de serviço no estabelecimento</option><option value="REGRA_CUSTOMIZADA">Regra customizada</option></select></div><p className="text-xs text-[var(--g3-muted)]">Candidaturas aprovadas na ordem registrada: {(candidaturas.data?.candidaturas ?? []).filter((item) => item.status === "APROVADA").map((item) => `${item.numero} — ${item.nomePublico}`).join(" · ") || "carregando..."}</p><textarea aria-label="Justificativa do desempate" className="min-h-20 w-full rounded-md border border-[var(--g3-border)] p-2 text-sm" placeholder="Descreva a ata ou justificativa da decisão." value={justificativa} onChange={(event) => setJustificativa(event.target.value)} /><Button onClick={() => void desempate.mutateAsync()} disabled={desempate.isPending || justificativa.trim().length < 10 || (candidaturas.data?.candidaturas ?? []).filter((item) => item.status === "APROVADA").length < 2}>{desempate.isPending ? "Registrando..." : "Registrar desempate"}</Button>{mensagem ? <p role="status" className="text-sm text-emerald-700">{mensagem}</p> : null}</CardContent></Card>;
  if (!resultado.data && !resultado.isLoading) return null;
  const grupos = [["TITULAR", "Titulares"], ["SUPLENTE", "Suplentes"], ["NAO_ELEITO", "Não eleitos"]] as const;
  return <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle>Resultado da eleição</CardTitle>{status === "APURACAO" ? <Button size="sm" onClick={() => void publicar.mutateAsync()} disabled={publicar.isPending}>{publicar.isPending ? "Publicando..." : "Publicar resultado"}</Button> : null}</div></CardHeader><CardContent>{resultado.isLoading ? <p className="text-sm text-[var(--g3-muted)]">Carregando apuração...</p> : resultado.data ? <div className="space-y-4"><div className="grid gap-2 sm:grid-cols-4"><p className="rounded-md bg-[var(--g3-card-soft)] p-2 text-sm">Eleitores: <strong>{resultado.data.totalEleitores}</strong></p><p className="rounded-md bg-[var(--g3-card-soft)] p-2 text-sm">Participantes: <strong>{resultado.data.totalParticipantes}</strong></p><p className="rounded-md bg-[var(--g3-card-soft)] p-2 text-sm">Votos válidos: <strong>{resultado.data.votosValidos}</strong></p><p className="rounded-md bg-[var(--g3-card-soft)] p-2 text-sm">Participação: <strong>{resultado.data.participacaoPercentual}%</strong></p></div>{grupos.map(([chave, titulo]) => <section key={chave}><h3 className="mb-2 text-sm font-semibold">{titulo}</h3><div className="space-y-2">{resultado.data.resultados.filter((item) => item.classificacao === chave).map((item) => <div key={item.candidaturaId} className="flex items-center justify-between rounded-md border border-[var(--g3-border)] p-3 text-sm"><span><strong>{item.numero} — {item.nome}</strong></span><span>{item.votos} voto(s)</span></div>)}{!resultado.data.resultados.some((item) => item.classificacao === chave) ? <p className="text-sm text-[var(--g3-muted)]">Nenhum registro.</p> : null}</div></section>)}</div> : null}</CardContent></Card>;
}
