import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { cipaService } from "@/services/cipa.service";

export function CipaImportadorEleitores({ eleicaoId, onConcluido }: { eleicaoId: string; onConcluido: () => void }) {
  const [arquivo, setArquivo] = useState<File>(); const [carregando, setCarregando] = useState(false); const [resultado, setResultado] = useState<Awaited<ReturnType<typeof cipaService.importarEleitores>>>(); const [erro, setErro] = useState("");
  async function importar() { if (!arquivo) return; setCarregando(true); setErro(""); setResultado(undefined); try { const data = await cipaService.importarEleitores(eleicaoId, arquivo); setResultado(data); onConcluido(); } catch { setErro("Não foi possível importar a planilha. Confira o formato e tente novamente."); } finally { setCarregando(false); } }
  return <Card><CardHeader><CardTitle>Importar eleitores</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-[var(--g3-muted)]">Use uma planilha CSV, XLS ou XLSX com as colunas: matrícula, nome, CPF, data de nascimento e data de admissão. Os colaboradores novos serão cadastrados no RH.</p><input className="block w-full rounded-md border border-[var(--g3-border)] p-2 text-sm" type="file" accept=".csv,.xls,.xlsx" onChange={(event) => setArquivo(event.target.files?.[0])} aria-label="Planilha de eleitores" /><Button onClick={() => void importar()} disabled={!arquivo || carregando}>{carregando ? "Importando..." : "Validar e importar"}</Button>{erro ? <p role="alert" className="text-sm text-red-700">{erro}</p> : null}{resultado ? <div role="status" className="rounded-md bg-[var(--g3-primary-soft)] p-3 text-sm"><p>{resultado.eleitoresIncluidos} eleitor(es) incluído(s), {resultado.colaboradoresCriados} colaborador(es) criado(s).</p>{resultado.inconsistencias.length ? <ul className="mt-2 list-disc pl-5">{resultado.inconsistencias.slice(0, 10).map((item) => <li key={`${item.linha}-${item.motivo}`}>Linha {item.linha}: {item.motivo}</li>)}</ul> : <p className="mt-1">Nenhuma inconsistência encontrada.</p>}</div> : null}</CardContent></Card>;
}
