import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useQueryClient, useMutation } from "@tanstack/react-query";
import { cipaService } from "@/services/cipa.service";
import type { CipaEleicao } from "@/types/cipa";

function dataFormulario(value: string) { return value ? value.slice(0, 10) : ""; }

export function CipaEditarEleicao({ eleicao, onConcluida }: { eleicao: CipaEleicao; onConcluida: () => void }) {
  const queryClient = useQueryClient();
  const [form, setForm] = useState({ nome: eleicao.nome, gestao: eleicao.gestao, inscricoesInicio: dataFormulario(eleicao.inscricoesInicio), inscricoesFim: dataFormulario(eleicao.inscricoesFim), votacaoInicio: dataFormulario(eleicao.votacaoInicio), votacaoFim: dataFormulario(eleicao.votacaoFim), titulares: eleicao.configuracao?.titulares ?? 1, suplentes: eleicao.configuracao?.suplentes ?? 1, votosPorEleitor: eleicao.configuracao?.votosPorEleitor ?? 1, permiteVotoBranco: eleicao.configuracao?.permiteVotoBranco ?? true, permiteVotoNulo: eleicao.configuracao?.permiteVotoNulo ?? true });
  const atualizar = (campo: string, valor: string | number | boolean) => setForm((atual) => ({ ...atual, [campo]: valor }));
  const salvar = useMutation({ mutationFn: () => cipaService.editarEleicao(eleicao.id, { unidadeId: eleicao.unidadeId, nome: form.nome, gestao: form.gestao, inscricoesInicio: form.inscricoesInicio, inscricoesFim: form.inscricoesFim, votacaoInicio: form.votacaoInicio, votacaoFim: form.votacaoFim, titulares: Number(form.titulares), suplentes: Number(form.suplentes), votosPorEleitor: Number(form.votosPorEleitor), permiteVotoBranco: form.permiteVotoBranco, permiteVotoNulo: form.permiteVotoNulo, permiteVotacaoCelular: eleicao.configuracao?.permiteVotacaoCelular ?? true, permiteVotacaoPresencial: eleicao.configuracao?.permiteVotacaoPresencial ?? false, regraDesempate: eleicao.configuracao?.regraDesempate ?? "TEMPO_SERVICO_ESTABELECIMENTO" }), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["cipa"] }); onConcluida(); } });
  return <Card><CardHeader><CardTitle>Editar eleição</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-[var(--g3-muted)]">A edição só está disponível enquanto a eleição estiver em configuração. As datas e regras serão validadas pelo servidor.</p><div className="grid gap-4 md:grid-cols-2"><div><Label htmlFor="cipa-editar-nome">Nome da eleição</Label><Input id="cipa-editar-nome" value={form.nome} onChange={(event) => atualizar("nome", event.target.value)} /></div><div><Label htmlFor="cipa-editar-gestao">Gestão</Label><Input id="cipa-editar-gestao" value={form.gestao} onChange={(event) => atualizar("gestao", event.target.value)} /></div>{([["inscricoesInicio", "Início das inscrições"], ["inscricoesFim", "Fim das inscrições"], ["votacaoInicio", "Início da votação"], ["votacaoFim", "Fim da votação"]] as const).map(([campo, label]) => <div key={campo}><Label htmlFor={`cipa-editar-${campo}`}>{label}</Label><Input id={`cipa-editar-${campo}`} type="date" value={form[campo]} onChange={(event) => atualizar(campo, event.target.value)} /></div>)}<div><Label htmlFor="cipa-editar-titulares">Titulares</Label><Input id="cipa-editar-titulares" type="number" min={1} value={form.titulares} onChange={(event) => atualizar("titulares", Number(event.target.value))} /></div><div><Label htmlFor="cipa-editar-suplentes">Suplentes</Label><Input id="cipa-editar-suplentes" type="number" min={0} value={form.suplentes} onChange={(event) => atualizar("suplentes", Number(event.target.value))} /></div><div><Label htmlFor="cipa-editar-votos">Votos permitidos por eleitor</Label><Input id="cipa-editar-votos" type="number" min={1} max={100} value={form.votosPorEleitor} onChange={(event) => atualizar("votosPorEleitor", Number(event.target.value))} /><p className="mt-1 text-xs text-[var(--g3-muted)]">Escolha quantos candidatos o eleitor poderá selecionar.</p></div></div>{salvar.isError ? <p role="alert" className="text-sm text-red-700">Não foi possível salvar a edição. Revise as datas e tente novamente.</p> : null}<div className="flex justify-end gap-2"><Button variant="outline" onClick={onConcluida}>Cancelar</Button><Button onClick={() => void salvar.mutateAsync()} disabled={salvar.isPending || !form.nome.trim() || !form.gestao.trim()}>{salvar.isPending ? "Salvando..." : "Salvar alterações"}</Button></div></CardContent></Card>;
}
