import { z } from "zod";
import { somenteDigitos, validarCep } from "@/lib/validators";

const telefoneObrigatorioSchema = z.string().refine((value) => {
  const totalDigitos = somenteDigitos(value).length;
  return totalDigitos === 10 || totalDigitos === 11;
}, "Informe o telefone principal.");

const telefoneOpcionalSchema = z.string().refine((value) => {
  if (!value.trim()) return true;
  const totalDigitos = somenteDigitos(value).length;
  return totalDigitos === 10 || totalDigitos === 11;
}, "Informe um telefone válido.");

const emailOpcionalSchema = z.preprocess(
  (value) => (typeof value === "string" ? value.trim().toLowerCase() : value),
  z.union([z.string().email("E-mail inválido."), z.literal("")]).optional()
);

export const beneficiarioStatusOptions = [
  "ATIVO",
  "INATIVO",
  "DESATUALIZADO",
  "INCOMPLETO",
  "EM_ANALISE",
  "BLOQUEADO"
] as const;

export const beneficiarioFormSchema = z.object({
  id_beneficiario: z.string().optional(),
  codigo: z.string().optional(),
  status: z.enum(beneficiarioStatusOptions),
  nome_completo: z.string().trim().min(3, "Informe o nome completo."),
  nome_social: z.string().optional(),
  apelido: z.string().optional(),
  data_nascimento: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Data de nascimento invalida."),
  foto_3x4: z.string().optional(),
  sexo_biologico: z.string().optional(),
  cor_raca: z.string().optional(),
  estado_civil: z.string().optional(),
  nacionalidade: z.string().optional(),
  naturalidade_cidade: z.string().optional(),
  naturalidade_uf: z.string().optional(),
  nome_mae: z.string().trim().min(3, "Informe o nome da mãe."),
  nome_pai: z.string().optional(),
  cpf: z.string().optional(),
  rg_numero: z.string().optional(),
  rg_orgao_emissor: z.string().optional(),
  rg_uf: z.string().optional(),
  rg_data_emissao: z.string().optional(),
  telefone_principal: telefoneObrigatorioSchema,
  telefone_secundario: telefoneOpcionalSchema.optional(),
  telefone_recado_nome: z.string().optional(),
  telefone_recado_numero: telefoneOpcionalSchema.optional(),
  email: emailOpcionalSchema,
  permite_contato_tel: z.boolean().default(true),
  permite_contato_whatsapp: z.boolean().default(true),
  permite_contato_sms: z.boolean().default(false),
  permite_contato_email: z.boolean().default(false),
  horario_preferencial_contato: z.string().optional(),
  cep: z.string().refine((value) => validarCep(value), "Informe um CEP válido."),
  logradouro: z.string().optional(),
  numero: z.string().optional(),
  complemento: z.string().optional(),
  bairro: z.string().optional(),
  ponto_referencia: z.string().optional(),
  municipio: z.string().optional(),
  uf: z.string().optional(),
  zona: z.string().optional(),
  subzona: z.string().optional(),
  mora_com_familia: z.boolean().default(false),
  responsavel_legal: z.boolean().default(false),
  vinculo_familiar: z.string().optional(),
  situacao_vulnerabilidade: z.string().optional(),
  composicao_familiar: z.string().optional(),
  criancas_adolescentes: z.number().int().nonnegative().optional(),
  idosos: z.number().int().nonnegative().optional(),
  acompanhamento_cras: z.boolean().default(false),
  acompanhamento_saude: z.boolean().default(false),
  participa_comunidade: z.string().optional(),
  rede_apoio: z.string().optional(),
  nivel_escolaridade: z.string().optional(),
  sabe_ler_escrever: z.boolean().default(false),
  estuda_atualmente: z.boolean().default(false),
  ocupacao: z.string().optional(),
  situacao_trabalho: z.string().optional(),
  local_trabalho: z.string().optional(),
  renda_mensal: z.string().optional(),
  fonte_renda: z.string().optional(),
  recebe_beneficio: z.boolean().default(false),
  beneficios_descricao: z.string().optional(),
  valor_total_beneficios: z.string().optional(),
  beneficios_recebidos: z.array(z.string()).optional(),
  possui_deficiencia: z.boolean().default(false),
  tipo_deficiencia: z.string().optional(),
  cid_principal: z.string().optional(),
  usa_medicacao_continua: z.boolean().default(false),
  descricao_medicacao: z.string().optional(),
  servico_saude_referencia: z.string().optional(),
  aceite_lgpd: z.boolean().refine((value) => value, "Confirme o aceite LGPD para salvar."),
  data_aceite_lgpd: z.string().optional(),
  observacoes: z.string().optional(),
  documentos_obrigatorios: z
    .array(
      z.object({
        id: z.string().optional(),
        nome: z.string(),
        numeroDocumento: z.string().optional(),
        nomeArquivo: z.string().optional(),
        caminhoArquivo: z.string().optional(),
        contentType: z.string().optional(),
        obrigatorio: z.boolean().optional(),
        ignorado: z.boolean().optional()
      })
    )
    .optional()
});

export type BeneficiarioFormValues = z.infer<typeof beneficiarioFormSchema>;

export const beneficiarioDefaultValues: BeneficiarioFormValues = {
  status: "EM_ANALISE",
  nome_completo: "",
  nome_social: "",
  apelido: "",
  data_nascimento: "",
  foto_3x4: "",
  sexo_biologico: "",
  cor_raca: "",
  estado_civil: "",
  nacionalidade: "",
  naturalidade_cidade: "",
  naturalidade_uf: "",
  nome_mae: "",
  nome_pai: "",
  cpf: "",
  rg_numero: "",
  rg_orgao_emissor: "",
  rg_uf: "",
  rg_data_emissao: "",
  telefone_principal: "",
  telefone_secundario: "",
  telefone_recado_nome: "",
  telefone_recado_numero: "",
  email: "",
  permite_contato_tel: true,
  permite_contato_whatsapp: true,
  permite_contato_sms: false,
  permite_contato_email: false,
  horario_preferencial_contato: "",
  cep: "",
  logradouro: "",
  numero: "",
  complemento: "",
  bairro: "",
  ponto_referencia: "",
  municipio: "",
  uf: "",
  zona: "URBANA",
  subzona: "",
  mora_com_familia: false,
  responsavel_legal: false,
  vinculo_familiar: "",
  situacao_vulnerabilidade: "",
  composicao_familiar: "",
  criancas_adolescentes: undefined,
  idosos: undefined,
  acompanhamento_cras: false,
  acompanhamento_saude: false,
  participa_comunidade: "",
  rede_apoio: "",
  nivel_escolaridade: "",
  sabe_ler_escrever: false,
  estuda_atualmente: false,
  ocupacao: "",
  situacao_trabalho: "",
  local_trabalho: "",
  renda_mensal: "",
  fonte_renda: "",
  recebe_beneficio: false,
  beneficios_descricao: "",
  valor_total_beneficios: "",
  beneficios_recebidos: [],
  possui_deficiencia: false,
  tipo_deficiencia: "",
  cid_principal: "",
  usa_medicacao_continua: false,
  descricao_medicacao: "",
  servico_saude_referencia: "",
  aceite_lgpd: true,
  data_aceite_lgpd: new Date().toISOString().slice(0, 10),
  observacoes: "",
  documentos_obrigatorios: []
};

