import { httpClient } from "./http-client";
import type { CipaColaborador, CipaDashboard, CipaEleicao } from "@/types/cipa";

type ListaEleicoes = { eleicoes: CipaEleicao[] };
type EleicaoPayload = {
  unidadeId: string; nome: string; gestao: string; descricao?: string; observacoes?: string;
  inscricoesInicio: string; inscricoesFim: string; divulgacaoCandidatosEm?: string; votacaoInicio: string; votacaoFim: string; apuracaoEm?: string; publicacaoPrevistaEm?: string; posseEm?: string;
  titulares: number; suplentes: number; votosPorEleitor: number;
  permiteVotoBranco: boolean; permiteVotoNulo: boolean; permiteVotacaoCelular?: boolean; permiteVotacaoPresencial?: boolean; regraDesempate?: string;
};

export const cipaService = {
  listarEleicoes() { return httpClient.get<ListaEleicoes>("/api/rh/cipa/eleicoes").then((response) => response.data); },
  criarEleicao(payload: EleicaoPayload) { return httpClient.post<CipaEleicao>("/api/rh/cipa/eleicoes", payload).then((response) => response.data); },
  editarEleicao(eleicaoId: string, payload: EleicaoPayload) { return httpClient.patch<CipaEleicao>(`/api/rh/cipa/eleicoes/${eleicaoId}`, payload).then((response) => response.data); },
  listarColaboradores(filtros?: { unidadeId?: string; termo?: string; status?: string; limite?: number }) { return httpClient.get<{ colaboradores: CipaColaborador[] }>("/api/rh/cipa/colaboradores", { params: { status: "ATIVO", limite: 50, ...filtros } }).then((response) => response.data); },
  criarColaborador(payload: { unidadeId: string; profissionalId?: string; matricula: string; nomeCompleto: string; cpf: string; dataNascimento: string; dataAdmissao: string; cargo?: string; setor?: string; turno?: string; email?: string; telefone?: string }) { return httpClient.post<CipaColaborador>("/api/rh/cipa/colaboradores", payload).then((response) => response.data); },
  listarEleitores(eleicaoId: string) { return httpClient.get<{ eleitores: Array<{ id: string; colaboradorId: string; nomeCompleto: string; matricula: string; cpfMascarado: string; status: string }> }>(`/api/rh/cipa/eleicoes/${eleicaoId}/eleitores`).then((response) => response.data); },
  adicionarEleitor(eleicaoId: string, colaboradorId: string) { return httpClient.post(`/api/rh/cipa/eleicoes/${eleicaoId}/eleitores`, { colaboradorId }).then((response) => response.data); },
  removerEleitor(eleicaoId: string, eleitorId: string) { return httpClient.delete(`/api/rh/cipa/eleicoes/${eleicaoId}/eleitores/${eleitorId}`).then((response) => response.data); },
  obterPortalPublico(identificador: string) { return httpClient.get<{ eleicao: { nome: string; gestao: string; status: string; votacaoInicio?: string; votacaoFim?: string }; candidatos: Array<{ id: string; numero: number; nomePublico: string; cargoPublico?: string; setorPublico?: string; apresentacao?: string; fotoUrl?: string }> }>(`/api/rh/cipa/portal/${encodeURIComponent(identificador)}`).then((response) => response.data); },
  dashboard(eleicaoId: string) { return httpClient.get<CipaDashboard>(`/api/rh/cipa/eleicoes/${eleicaoId}/dashboard`).then((response) => response.data); },
  publicar(eleicaoId: string) { return httpClient.post<CipaEleicao>(`/api/rh/cipa/eleicoes/${eleicaoId}/publicar`).then((response) => response.data); },
  gerarZeresima(eleicaoId: string) { return httpClient.post(`/api/rh/cipa/eleicoes/${eleicaoId}/zeresima`).then((response) => response.data); },
  abrirVotacao(eleicaoId: string) { return httpClient.post<CipaEleicao>(`/api/rh/cipa/eleicoes/${eleicaoId}/abrir-votacao`).then((response) => response.data); },
  encerrarVotacao(eleicaoId: string) { return httpClient.post<CipaEleicao>(`/api/rh/cipa/eleicoes/${eleicaoId}/encerrar-votacao`).then((response) => response.data); },
  apurar(eleicaoId: string) { return httpClient.post(`/api/rh/cipa/eleicoes/${eleicaoId}/apurar`).then((response) => response.data); },
  buscarApuracao(eleicaoId: string) { return httpClient.get<{ resultados: Array<{ candidaturaId: string; numero: number; nome: string; votos: number; classificacao: string }>; totalEleitores: number; totalParticipantes: number; totalVotos: number; votosValidos: number; votosBrancos: number; votosNulos: number; participacaoPercentual: number; apuradaEm: string }>(`/api/rh/cipa/eleicoes/${eleicaoId}/apuracao`).then((response) => response.data); },
  publicarResultado(eleicaoId: string) { return httpClient.post(`/api/rh/cipa/eleicoes/${eleicaoId}/publicar-resultado`).then((response) => response.data); },
  registrarDesempate(eleicaoId: string, itens: Array<{ candidaturaId: string; ordem: number; criterio: "TEMPO_SERVICO_ESTABELECIMENTO" | "SORTEIO_AUDITADO" | "REGRA_CUSTOMIZADA"; justificativa: string }>) { return httpClient.post(`/api/rh/cipa/eleicoes/${eleicaoId}/desempates`, { itens }).then((response) => response.data); },
  abrirInscricoes(eleicaoId: string) { return httpClient.post<CipaEleicao>(`/api/rh/cipa/eleicoes/${eleicaoId}/abrir-inscricoes`).then((response) => response.data); },
  encerrarInscricoes(eleicaoId: string) { return httpClient.post<CipaEleicao>(`/api/rh/cipa/eleicoes/${eleicaoId}/encerrar-inscricoes`).then((response) => response.data); },
  cancelarEleicao(eleicaoId: string, motivo: string) { return httpClient.post<CipaEleicao>(`/api/rh/cipa/eleicoes/${eleicaoId}/cancelar`, { motivo }).then((response) => response.data); },
  importarEleitores(eleicaoId: string, arquivo: File) { const form = new FormData(); form.append("arquivo", arquivo); return httpClient.post<{ totalLinhas: number; colaboradoresCriados: number; colaboradoresExistentes: number; eleitoresIncluidos: number; inconsistencias: Array<{ linha: number; motivo: string }> }>(`/api/rh/cipa/eleicoes/${eleicaoId}/eleitores/importar`, form, { headers: { "Content-Type": "multipart/form-data" }, timeout: 120000 }).then((response) => response.data); },
  autenticarEleitor(identificador: string, payload: { cpf: string; dataNascimento: string }) { return httpClient.post<{ token: string; colaborador: { nome: string }; eleicao: { nome: string; gestao: string } }>(`/api/rh/cipa/portal/${identificador}/autenticar-eleitor`, payload).then((response) => response.data); },
  autenticarCandidato(identificador: string, payload: { cpf: string; dataNascimento: string }) { return httpClient.post<{ token: string; colaborador: { nome: string }; eleicao: { nome: string; gestao: string } }>(`/api/rh/cipa/portal/${identificador}/autenticar-candidato`, payload).then((response) => response.data); },
  enviarCandidatura(identificador: string, token: string, payload: { apresentacao?: string; proposta?: string; declaracaoCiencia: true }) { return httpClient.post<{ protocolo: string }>(`/api/rh/cipa/portal/${identificador}/candidatura`, payload, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.data); },
  enviarFotoCandidatura(identificador: string, token: string, arquivo: File) { const form = new FormData(); form.append("arquivo", arquivo); return httpClient.post<{ caminhoLogico: string; nomeArquivo: string }>(`/api/rh/cipa/portal/${identificador}/candidatura/foto`, form, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.data); },
  obterUrna(identificador: string, token: string) { return httpClient.get<{ candidatos: Array<{ id: string; numero: number; nome_publico: string; cargo_publico?: string; setor_publico?: string; apresentacao?: string; foto_url?: string }>; eleicao: { nome: string; gestao: string; votos_por_eleitor: number; permite_voto_branco: boolean; permite_voto_nulo: boolean } }>(`/api/rh/cipa/portal/${identificador}/urna`, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.data); },
  registrarVoto(identificador: string, token: string, payload: { tipo: "VALIDO" | "BRANCO" | "NULO"; candidaturaIds?: string[]; candidaturaId?: string }) { return httpClient.post<{ protocolo: string }>(`/api/rh/cipa/portal/${identificador}/voto`, payload, { headers: { Authorization: `Bearer ${token}` } }).then((response) => response.data); },
  gerarDocumento(eleicaoId: string, tipo: "EDITAL" | "COMUNICADO" | "RELACAO_CANDIDATOS" | "ZERESIMA" | "APURACAO" | "RESULTADO_OFICIAL" | "ATA_ELEICAO" | "ATA_POSSE") { return httpClient.post<{ caminhoLogico: string; nomeArquivo: string }>(`/api/rh/cipa/eleicoes/${eleicaoId}/documentos`, { tipo }).then((response) => response.data); },
  listarAuditoria(eleicaoId: string) { return httpClient.get<{ auditoria: Array<{ id: string; acao: string; resultado: string; criadoEm: string; detalhes: unknown }> }>(`/api/rh/cipa/eleicoes/${eleicaoId}/auditoria`).then((response) => response.data); },
  listarDocumentos(eleicaoId: string) { return httpClient.get<{ documentos: Array<{ id: string; tipo: string; versao: number; nomeArquivo: string; criadoEm: string }> }>(`/api/rh/cipa/eleicoes/${eleicaoId}/documentos`).then((response) => response.data); },
  baixarDocumento(eleicaoId: string, documentoId: string) { return httpClient.get<Blob>(`/api/rh/cipa/eleicoes/${eleicaoId}/documentos/${documentoId}/conteudo`, { responseType: "blob" }).then((response) => response.data); },
  baixarRelatorio(eleicaoId: string, tipo: "ELEITORES_APTOS" | "ELEITORES_VOTARAM" | "ELEITORES_PENDENTES" | "CANDIDATOS" | "PARTICIPACAO" | "APURACAO" | "RESULTADO_FINAL" | "AUDITORIA" | "HISTORICO") { return httpClient.get<Blob>(`/api/rh/cipa/eleicoes/${eleicaoId}/relatorios`, { params: { tipo }, responseType: "blob" }).then((response) => response.data); },
  listarCandidaturas(eleicaoId: string) { return httpClient.get<{ candidaturas: Array<{ id: string; numero: number; nomePublico: string; status: string; protocolo: string; apresentacao?: string; proposta?: string }> }>(`/api/rh/cipa/eleicoes/${eleicaoId}/candidaturas`).then((response) => response.data); },
  criarCandidatura(eleicaoId: string, payload: { colaboradorId: string; apresentacao?: string; proposta?: string; declaracaoCiencia: boolean }) { return httpClient.post(`/api/rh/cipa/eleicoes/${eleicaoId}/candidaturas`, payload).then((response) => response.data as { id: string }); },
  alterarStatusCandidatura(eleicaoId: string, candidaturaId: string, status: "APROVADA" | "REPROVADA" | "CORRECAO_SOLICITADA" | "DESISTENTE", motivo?: string) { return httpClient.patch(`/api/rh/cipa/eleicoes/${eleicaoId}/candidaturas/${candidaturaId}/status`, { status, motivo }).then((response) => response.data); },
  listarComissao(eleicaoId: string) { return httpClient.get<{ membros: Array<{ id: string; nome: string; funcao: string; colaboradorId?: string }> }>(`/api/rh/cipa/eleicoes/${eleicaoId}/comissao`).then((response) => response.data); },
  adicionarComissao(eleicaoId: string, payload: { nome: string; funcao: string; colaboradorId?: string }) { return httpClient.post(`/api/rh/cipa/eleicoes/${eleicaoId}/comissao`, payload).then((response) => response.data); },
  removerComissao(eleicaoId: string, membroId: string) { return httpClient.delete(`/api/rh/cipa/eleicoes/${eleicaoId}/comissao/${membroId}`).then((response) => response.data); },
  estenderVotacao(eleicaoId: string, dias = 2) { return httpClient.post<CipaEleicao>(`/api/rh/cipa/eleicoes/${eleicaoId}/estender-votacao`, { dias }).then((response) => response.data); }
};
