import { useEffect, useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { educacionalService, type EducacionalRecurso } from "@/services/educacional.service";
import type { EducacionalItem } from "@/types/educacional";

type RecursoGestao = "ocorrencias" | "agenda";
function texto(item: EducacionalItem, ...chaves: string[]) { for (const chave of chaves) { const valor = item[chave]; if (valor !== null && valor !== undefined && String(valor).trim()) return String(valor); } return `Registro #${item.id}`; }

export function EducacionalGestaoPage({ recurso }: { recurso: RecursoGestao }) {
  const [listas, setListas] = useState<Record<string, EducacionalItem[]>>({});
  const [formulario, setFormulario] = useState({ aluno_id: "", matricula_id: "", data_ocorrencia: new Date().toISOString().slice(0, 10), tipo: "", descricao: "", providencias: "", turma_id: "", data_inicio: "", tipo_agenda: "", titulo: "", descricao_agenda: "" });
  const [mensagem, setMensagem] = useState("");
  const [carregando, setCarregando] = useState(false);
  const alterar = (campo: keyof typeof formulario, valor: string) => setFormulario((anterior) => ({ ...anterior, [campo]: valor }));
  const opcoes = (itens: EducacionalItem[] | undefined, chaves: string[]) => (itens ?? []).map((item) => <option key={item.id} value={item.id}>{texto(item, ...chaves)}</option>);
  const carregar = async () => { setCarregando(true); try { const recursos: EducacionalRecurso[] = recurso === "ocorrencias" ? ["ocorrencias", "alunos", "matriculas"] : ["agenda", "turmas"]; const respostas = await Promise.all(recursos.map((item) => educacionalService.listar(item))); setListas(Object.fromEntries(recursos.map((item, index) => [item, respostas[index]]))); } catch (erro) { setMensagem(erro instanceof Error ? erro.message : "Não foi possível carregar os registros."); } finally { setCarregando(false); } };
  useEffect(() => { void carregar(); }, [recurso]);
  async function salvar(event: FormEvent) { event.preventDefault(); const ocorrencia = recurso === "ocorrencias"; const obrigatorios = ocorrencia ? [formulario.aluno_id, formulario.data_ocorrencia, formulario.tipo, formulario.descricao] : [formulario.data_inicio, formulario.tipo_agenda, formulario.titulo]; if (obrigatorios.some((valor) => !valor)) { setMensagem("Preencha os campos obrigatórios."); return; } setCarregando(true); try { const payload = ocorrencia ? { aluno_id: Number(formulario.aluno_id), matricula_id: formulario.matricula_id ? Number(formulario.matricula_id) : null, data_ocorrencia: formulario.data_ocorrencia, tipo: formulario.tipo, descricao: formulario.descricao, providencias: formulario.providencias || null, responsavel_comunicado: false, status: "ABERTA" } : { turma_id: formulario.turma_id ? Number(formulario.turma_id) : null, data_inicio: new Date(formulario.data_inicio).toISOString(), tipo: formulario.tipo_agenda, titulo: formulario.titulo, descricao: formulario.descricao_agenda || null, status: "ATIVO" }; await educacionalService.salvar(recurso, payload); setMensagem(ocorrencia ? "Ocorrência registrada." : "Evento adicionado à agenda escolar."); await carregar(); } catch (erro) { setMensagem(erro instanceof Error ? erro.message : "Não foi possível salvar o registro."); } finally { setCarregando(false); } }
  const itens = listas[recurso] ?? [];
  return <div className="grid gap-4 lg:grid-cols-[minmax(0,440px)_1fr]"><Card><CardHeader><CardTitle>{recurso === "ocorrencias" ? "Ocorrências" : "Agenda escolar"}</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={salvar}>{recurso === "ocorrencias" ? <><Select value={formulario.aluno_id} onChange={(event) => alterar("aluno_id", event.target.value)}><option value="">Aluno</option>{opcoes(listas.alunos, ["beneficiario_id", "numero_aluno"])}</Select><Input type="date" value={formulario.data_ocorrencia} onChange={(event) => alterar("data_ocorrencia", event.target.value)} /><Input value={formulario.tipo} onChange={(event) => alterar("tipo", event.target.value)} placeholder="Tipo de ocorrência" /><textarea className="min-h-24 w-full rounded-md border border-[var(--g3-border)] bg-[var(--g3-card)] p-3 text-sm" value={formulario.descricao} onChange={(event) => alterar("descricao", event.target.value)} placeholder="Descrição" /><textarea className="min-h-20 w-full rounded-md border border-[var(--g3-border)] bg-[var(--g3-card)] p-3 text-sm" value={formulario.providencias} onChange={(event) => alterar("providencias", event.target.value)} placeholder="Providências" /></> : <><Select value={formulario.turma_id} onChange={(event) => alterar("turma_id", event.target.value)}><option value="">Turma (opcional)</option>{opcoes(listas.turmas, ["nome"])}</Select><Input type="datetime-local" value={formulario.data_inicio} onChange={(event) => alterar("data_inicio", event.target.value)} /><Input value={formulario.tipo_agenda} onChange={(event) => alterar("tipo_agenda", event.target.value)} placeholder="Tipo de evento" /><Input value={formulario.titulo} onChange={(event) => alterar("titulo", event.target.value)} placeholder="Título" /><textarea className="min-h-24 w-full rounded-md border border-[var(--g3-border)] bg-[var(--g3-card)] p-3 text-sm" value={formulario.descricao_agenda} onChange={(event) => alterar("descricao_agenda", event.target.value)} placeholder="Descrição" /></>}<Button disabled={carregando}>Salvar</Button></form>{mensagem ? <p className="mt-3 text-sm text-[var(--g3-muted)]">{mensagem}</p> : null}</CardContent></Card><Card><CardHeader><CardTitle>Registros salvos</CardTitle></CardHeader><CardContent className="space-y-2">{itens.map((item) => <div key={item.id} className="rounded-lg border border-[var(--g3-border)] bg-[var(--g3-card-soft)] p-3 text-sm">{recurso === "ocorrencias" ? `${texto(item, "tipo")} · ${texto(item, "data_ocorrencia")}` : `${texto(item, "titulo")} · ${texto(item, "data_inicio")}`}</div>)}{!itens.length ? <p className="text-sm text-[var(--g3-muted)]">Nenhum registro encontrado.</p> : null}</CardContent></Card></div>;
}
