import { useEffect, useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { educacionalService } from "@/services/educacional.service";
import { profissionaisService } from "@/services/profissionais.service";
import type { Profissional } from "@/types/profissional";
import type { EducacionalItem } from "@/types/educacional";

export function EducacionalProfissionaisPage() {
  const [profissionais, setProfissionais] = useState<Profissional[]>([]);
  const [vinculos, setVinculos] = useState<EducacionalItem[]>([]);
  const [form, setForm] = useState({ profissional_id: "", funcao: "", carga_horaria: "", observacoes: "" });
  const [mensagem, setMensagem] = useState(""); const [carregando, setCarregando] = useState(false);
  const carregar = async () => { setCarregando(true); try { const [p, v] = await Promise.all([profissionaisService.listar({ status: "ATIVO" }), educacionalService.listar("profissionais")]); setProfissionais(p.profissionais); setVinculos(v); } catch (erro) { setMensagem(erro instanceof Error ? erro.message : "Não foi possível carregar a equipe pedagógica."); } finally { setCarregando(false); } };
  useEffect(() => { void carregar(); }, []);
  async function salvar(event: FormEvent) { event.preventDefault(); if (!form.profissional_id || form.funcao.trim().length < 2) { setMensagem("Selecione o profissional e informe a função."); return; } setCarregando(true); try { await educacionalService.salvar("profissionais", { profissional_id: Number(form.profissional_id), funcao: form.funcao.trim(), carga_horaria: form.carga_horaria ? Number(form.carga_horaria) : null, observacoes: form.observacoes.trim() || null, status: "ATIVO" }); setForm({ profissional_id: "", funcao: "", carga_horaria: "", observacoes: "" }); setMensagem("Vínculo educacional salvo com sucesso."); await carregar(); } catch (erro) { setMensagem(erro instanceof Error ? erro.message : "Não foi possível salvar o vínculo educacional."); } finally { setCarregando(false); } }
  return <div className="grid gap-4 lg:grid-cols-[minmax(0,440px)_1fr]"><Card><CardHeader><CardTitle>Vínculo da equipe pedagógica</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={salvar}><Select value={form.profissional_id} onChange={(event) => setForm((anterior) => ({ ...anterior, profissional_id: event.target.value }))}><option value="">Profissional do cadastro central</option>{profissionais.map((item) => <option key={item.id_profissional} value={item.id_profissional}>{item.nome_completo} · {item.categoria}</option>)}</Select><Input value={form.funcao} onChange={(event) => setForm((anterior) => ({ ...anterior, funcao: event.target.value }))} placeholder="Função educacional" /><Input type="number" min="0" value={form.carga_horaria} onChange={(event) => setForm((anterior) => ({ ...anterior, carga_horaria: event.target.value }))} placeholder="Carga horária semanal" /><textarea className="min-h-20 w-full rounded-md border border-[var(--g3-border)] bg-[var(--g3-card)] p-3 text-sm" value={form.observacoes} onChange={(event) => setForm((anterior) => ({ ...anterior, observacoes: event.target.value }))} placeholder="Observações" /><Button type="submit" disabled={carregando}>{carregando ? "Salvando..." : "Salvar vínculo"}</Button></form>{mensagem ? <p className="mt-3 text-sm text-[var(--g3-muted)]">{mensagem}</p> : null}</CardContent></Card><Card><CardHeader><CardTitle>Equipe vinculada</CardTitle></CardHeader><CardContent className="space-y-2">{vinculos.map((item) => <div key={item.id} className="rounded-lg border border-[var(--g3-border)] bg-[var(--g3-card-soft)] p-3 text-sm"><strong>{String(item.profissional_nome ?? `Profissional #${item.profissional_id}`)}</strong><span className="ml-2 text-xs text-[var(--g3-muted)]">{String(item.funcao ?? "")} · {String(item.status ?? "")}</span></div>)}{!vinculos.length ? <p className="text-sm text-[var(--g3-muted)]">Nenhum vínculo educacional encontrado.</p> : null}</CardContent></Card></div>;
}
