import { useEffect, useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { educacionalService } from "@/services/educacional.service";
import type { EducacionalItem } from "@/types/educacional";

type RecursoPlanejamento = "planos-aula" | "planejamentos";
function texto(item: EducacionalItem, ...chaves: string[]) { for (const chave of chaves) { const valor = item[chave]; if (valor !== null && valor !== undefined && String(valor).trim()) return String(valor); } return `Registro #${item.id}`; }

export function EducacionalPlanejamentoPage({ recurso }: { recurso: RecursoPlanejamento }) {
  const [listas, setListas] = useState<Record<string, EducacionalItem[]>>({});
  const [formulario, setFormulario] = useState({ turma_id: "", disciplina_id: "", data_aula: "", tema: "", objetivos: "", conteudo: "", metodologia: "", ano_letivo_id: "", periodo: "", titulo: "", estrategias: "", metas: "" });
  const [mensagem, setMensagem] = useState("");
  const [carregando, setCarregando] = useState(false);
  const alterar = (campo: keyof typeof formulario, valor: string) => setFormulario((anterior) => ({ ...anterior, [campo]: valor }));
  const opcoes = (itens: EducacionalItem[] | undefined, chaves: string[]) => (itens ?? []).map((item) => <option key={item.id} value={item.id}>{texto(item, ...chaves)}</option>);
  const carregar = async () => { setCarregando(true); try { const recursos = recurso === "planos-aula" ? ["planos-aula", "turmas", "disciplinas"] : ["planejamentos", "anos-letivos"]; const respostas = await Promise.all(recursos.map((item) => educacionalService.listar(item as never))); setListas(Object.fromEntries(recursos.map((item, index) => [item, respostas[index]]))); } catch (erro) { setMensagem(erro instanceof Error ? erro.message : "Não foi possível carregar o planejamento."); } finally { setCarregando(false); } };
  useEffect(() => { void carregar(); }, [recurso]);
  async function salvar(event: FormEvent) { event.preventDefault(); const plano = recurso === "planos-aula"; const obrigatorios = plano ? [formulario.turma_id, formulario.disciplina_id, formulario.tema] : [formulario.ano_letivo_id, formulario.periodo, formulario.titulo]; if (obrigatorios.some((valor) => !valor)) { setMensagem("Preencha os campos obrigatórios."); return; } setCarregando(true); try { const payload = plano ? { turma_id: Number(formulario.turma_id), disciplina_id: Number(formulario.disciplina_id), data_aula: formulario.data_aula || null, tema: formulario.tema, objetivos: formulario.objetivos || null, conteudo: formulario.conteudo || null, metodologia: formulario.metodologia || null, status: "PLANEJADO" } : { ano_letivo_id: Number(formulario.ano_letivo_id), periodo: formulario.periodo, titulo: formulario.titulo, objetivos: formulario.objetivos || null, estrategias: formulario.estrategias || null, metas: formulario.metas || null, status: "PLANEJADO" }; await educacionalService.salvar(recurso, payload); setMensagem(plano ? "Plano de aula salvo." : "Planejamento pedagógico salvo."); await carregar(); } catch (erro) { setMensagem(erro instanceof Error ? erro.message : "Não foi possível salvar o planejamento."); } finally { setCarregando(false); } }
  const itens = listas[recurso] ?? [];
  return <div className="grid gap-4 lg:grid-cols-[minmax(0,460px)_1fr]"><Card><CardHeader><CardTitle>{recurso === "planos-aula" ? "Plano de aula" : "Planejamento pedagógico"}</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={salvar}>{recurso === "planos-aula" ? <><Select value={formulario.turma_id} onChange={(event) => alterar("turma_id", event.target.value)}><option value="">Turma</option>{opcoes(listas.turmas, ["nome"])}</Select><Select value={formulario.disciplina_id} onChange={(event) => alterar("disciplina_id", event.target.value)}><option value="">Componente curricular</option>{opcoes(listas.disciplinas, ["nome"])}</Select><Input type="date" value={formulario.data_aula} onChange={(event) => alterar("data_aula", event.target.value)} /><Input value={formulario.tema} onChange={(event) => alterar("tema", event.target.value)} placeholder="Tema" /><textarea className="min-h-24 w-full rounded-md border border-[var(--g3-border)] bg-[var(--g3-card)] p-3 text-sm" value={formulario.objetivos} onChange={(event) => alterar("objetivos", event.target.value)} placeholder="Objetivos" /><textarea className="min-h-24 w-full rounded-md border border-[var(--g3-border)] bg-[var(--g3-card)] p-3 text-sm" value={formulario.conteudo} onChange={(event) => alterar("conteudo", event.target.value)} placeholder="Conteúdo e metodologia" /></> : <><Select value={formulario.ano_letivo_id} onChange={(event) => alterar("ano_letivo_id", event.target.value)}><option value="">Ano letivo</option>{opcoes(listas["anos-letivos"], ["ano", "descricao"])}</Select><Input value={formulario.periodo} onChange={(event) => alterar("periodo", event.target.value)} placeholder="Período (ex.: 1º bimestre)" /><Input value={formulario.titulo} onChange={(event) => alterar("titulo", event.target.value)} placeholder="Título" /><textarea className="min-h-24 w-full rounded-md border border-[var(--g3-border)] bg-[var(--g3-card)] p-3 text-sm" value={formulario.objetivos} onChange={(event) => alterar("objetivos", event.target.value)} placeholder="Objetivos" /><textarea className="min-h-24 w-full rounded-md border border-[var(--g3-border)] bg-[var(--g3-card)] p-3 text-sm" value={formulario.estrategias} onChange={(event) => alterar("estrategias", event.target.value)} placeholder="Estratégias e metas" /></>}<Button disabled={carregando}>Salvar</Button></form>{mensagem ? <p className="mt-3 text-sm text-[var(--g3-muted)]">{mensagem}</p> : null}</CardContent></Card><Card><CardHeader><CardTitle>Registros salvos</CardTitle></CardHeader><CardContent className="space-y-2">{itens.map((item) => <div key={item.id} className="rounded-lg border border-[var(--g3-border)] bg-[var(--g3-card-soft)] p-3 text-sm">{recurso === "planos-aula" ? `${texto(item, "tema")} · ${texto(item, "status")}` : `${texto(item, "titulo")} · ${texto(item, "periodo")}`}</div>)}{!itens.length ? <p className="text-sm text-[var(--g3-muted)]">Nenhum registro encontrado.</p> : null}</CardContent></Card></div>;
}
