import { useEffect, useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { educacionalService, type EducacionalRecurso } from "@/services/educacional.service";
import type { EducacionalItem } from "@/types/educacional";

type AbaDiario = "diarios" | "frequencias";
function nome(item: EducacionalItem, ...chaves: string[]) { for (const chave of chaves) { const valor = item[chave]; if (valor !== null && valor !== undefined && String(valor).trim()) return String(valor); } return `Registro #${item.id}`; }

export function EducacionalDiarioPage({ recurso }: { recurso: AbaDiario }) {
  const [listas, setListas] = useState<Record<string, EducacionalItem[]>>({});
  const [formulario, setFormulario] = useState({ turma_id: "", disciplina_id: "", data_aula: new Date().toISOString().slice(0, 10), conteudo: "", diario_aula_id: "", matricula_id: "", situacao: "PRESENTE" });
  const [mensagem, setMensagem] = useState("");
  const [carregando, setCarregando] = useState(false);
  const alterar = (campo: keyof typeof formulario, valor: string) => setFormulario((anterior) => ({ ...anterior, [campo]: valor }));
  const opcoes = (itens: EducacionalItem[] | undefined, chaves: string[]) => (itens ?? []).map((item) => <option key={item.id} value={item.id}>{nome(item, ...chaves)}</option>);
  const carregar = async () => { setCarregando(true); try { const recursos: EducacionalRecurso[] = recurso === "diarios" ? ["diarios", "turmas", "disciplinas"] : ["frequencias", "diarios", "matriculas"]; const respostas = await Promise.all(recursos.map((item) => educacionalService.listar(item))); setListas(Object.fromEntries(recursos.map((item, index) => [item, respostas[index]]))); } catch (erro) { setMensagem(erro instanceof Error ? erro.message : "Não foi possível carregar o diário."); } finally { setCarregando(false); } };
  useEffect(() => { void carregar(); }, [recurso]);
  async function salvar(event: FormEvent) { event.preventDefault(); const diario = recurso === "diarios"; const obrigatorios = diario ? [formulario.turma_id, formulario.disciplina_id, formulario.data_aula, formulario.conteudo] : [formulario.diario_aula_id, formulario.matricula_id, formulario.situacao]; if (obrigatorios.some((valor) => !valor)) { setMensagem("Preencha os campos obrigatórios."); return; } setCarregando(true); try { const payload = diario ? { turma_id: Number(formulario.turma_id), disciplina_id: Number(formulario.disciplina_id), data_aula: formulario.data_aula, conteudo: formulario.conteudo, status: "FINALIZADO" } : { diario_aula_id: Number(formulario.diario_aula_id), matricula_id: Number(formulario.matricula_id), situacao: formulario.situacao }; await educacionalService.salvar(recurso, payload); setMensagem(diario ? "Aula registrada no diário." : "Frequência registrada."); await carregar(); } catch (erro) { setMensagem(erro instanceof Error ? erro.message : "Não foi possível salvar o registro."); } finally { setCarregando(false); } }
  const itens = listas[recurso] ?? [];
  return <div className="grid gap-4 lg:grid-cols-[minmax(0,420px)_1fr]"><Card><CardHeader><CardTitle>{recurso === "diarios" ? "Diário de classe" : "Chamada/Frequência"}</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={salvar}>{recurso === "diarios" ? <><Select value={formulario.turma_id} onChange={(event) => alterar("turma_id", event.target.value)}><option value="">Turma</option>{opcoes(listas.turmas, ["nome"])}</Select><Select value={formulario.disciplina_id} onChange={(event) => alterar("disciplina_id", event.target.value)}><option value="">Componente curricular</option>{opcoes(listas.disciplinas, ["nome"])}</Select><Input type="date" value={formulario.data_aula} onChange={(event) => alterar("data_aula", event.target.value)} /><textarea className="min-h-32 w-full rounded-md border border-[var(--g3-border)] bg-[var(--g3-card)] p-3 text-sm" value={formulario.conteudo} onChange={(event) => alterar("conteudo", event.target.value)} placeholder="Conteúdo ministrado" /> </> : <><Select value={formulario.diario_aula_id} onChange={(event) => alterar("diario_aula_id", event.target.value)}><option value="">Aula</option>{opcoes(listas.diarios, ["data_aula", "id"])}</Select><Select value={formulario.matricula_id} onChange={(event) => alterar("matricula_id", event.target.value)}><option value="">Matrícula do aluno</option>{opcoes(listas.matriculas, ["numero_matricula", "aluno_id"])}</Select><Select value={formulario.situacao} onChange={(event) => alterar("situacao", event.target.value)}><option value="PRESENTE">Presente</option><option value="AUSENTE">Ausente</option><option value="JUSTIFICADO">Justificado</option><option value="ATRASO">Atraso</option><option value="SAIDA_ANTECIPADA">Saída antecipada</option></Select></>}<Button disabled={carregando}>Salvar</Button></form>{mensagem ? <p className="mt-3 text-sm text-[var(--g3-muted)]">{mensagem}</p> : null}</CardContent></Card><Card><CardHeader><CardTitle>Registros salvos</CardTitle></CardHeader><CardContent className="space-y-2">{itens.map((item) => <div key={item.id} className="rounded-lg border border-[var(--g3-border)] bg-[var(--g3-card-soft)] p-3 text-sm">{recurso === "diarios" ? `${nome(item, "data_aula")} · Turma ${nome(item, "turma_id")} · ${nome(item, "conteudo")}` : `${nome(item, "diario_aula_id")} · Matrícula ${nome(item, "matricula_id")} · ${nome(item, "situacao")}`}</div>)}{!itens.length ? <p className="text-sm text-[var(--g3-muted)]">Nenhum registro encontrado.</p> : null}</CardContent></Card></div>;
}
