import { useEffect, useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { educacionalService, type EducacionalRecurso } from "@/services/educacional.service";
import type { EducacionalItem } from "@/types/educacional";

type RecursoAvaliacao = "avaliacoes" | "notas";
function texto(item: EducacionalItem, ...chaves: string[]) { for (const chave of chaves) { const valor = item[chave]; if (valor !== null && valor !== undefined && String(valor).trim()) return String(valor); } return `Registro #${item.id}`; }

export function EducacionalAvaliacoesPage({ recurso }: { recurso: RecursoAvaliacao }) {
  const [listas, setListas] = useState<Record<string, EducacionalItem[]>>({});
  const [formulario, setFormulario] = useState({ turma_id: "", disciplina_id: "", periodo: "", tipo: "", data_avaliacao: "", valor_maximo: "10", peso: "1", avaliacao_id: "", matricula_id: "", valor: "", conceito: "" });
  const [mensagem, setMensagem] = useState("");
  const [carregando, setCarregando] = useState(false);
  const alterar = (campo: keyof typeof formulario, valor: string) => setFormulario((anterior) => ({ ...anterior, [campo]: valor }));
  const opcoes = (itens: EducacionalItem[] | undefined, chaves: string[]) => (itens ?? []).map((item) => <option key={item.id} value={item.id}>{texto(item, ...chaves)}</option>);
  const carregar = async () => { setCarregando(true); try { const recursos: EducacionalRecurso[] = recurso === "avaliacoes" ? ["avaliacoes", "turmas", "disciplinas"] : ["notas", "avaliacoes", "matriculas"]; const respostas = await Promise.all(recursos.map((item) => educacionalService.listar(item))); setListas(Object.fromEntries(recursos.map((item, index) => [item, respostas[index]]))); } catch (erro) { setMensagem(erro instanceof Error ? erro.message : "Não foi possível carregar as avaliações."); } finally { setCarregando(false); } };
  useEffect(() => { void carregar(); }, [recurso]);
  async function salvar(event: FormEvent) { event.preventDefault(); const avaliacao = recurso === "avaliacoes"; const obrigatorios = avaliacao ? [formulario.turma_id, formulario.disciplina_id, formulario.periodo, formulario.tipo] : [formulario.avaliacao_id, formulario.matricula_id, formulario.valor]; if (obrigatorios.some((valor) => !valor)) { setMensagem("Preencha os campos obrigatórios."); return; } setCarregando(true); try { const payload = avaliacao ? { turma_id: Number(formulario.turma_id), disciplina_id: Number(formulario.disciplina_id), periodo: formulario.periodo, tipo: formulario.tipo, data_avaliacao: formulario.data_avaliacao || null, valor_maximo: Number(formulario.valor_maximo), peso: Number(formulario.peso), status: "ABERTA" } : { avaliacao_id: Number(formulario.avaliacao_id), matricula_id: Number(formulario.matricula_id), valor: Number(formulario.valor), conceito: formulario.conceito || null }; await educacionalService.salvar(recurso, payload); setMensagem(avaliacao ? "Avaliação cadastrada." : "Nota lançada com sucesso."); await carregar(); } catch (erro) { setMensagem(erro instanceof Error ? erro.message : "Não foi possível salvar o registro."); } finally { setCarregando(false); } }
  const itens = listas[recurso] ?? [];
  return <div className="grid gap-4 lg:grid-cols-[minmax(0,440px)_1fr]"><Card><CardHeader><CardTitle>{recurso === "avaliacoes" ? "Avaliações" : "Lançamento de notas"}</CardTitle></CardHeader><CardContent><form className="space-y-3" onSubmit={salvar}>{recurso === "avaliacoes" ? <><Select value={formulario.turma_id} onChange={(event) => alterar("turma_id", event.target.value)}><option value="">Turma</option>{opcoes(listas.turmas, ["nome"])}</Select><Select value={formulario.disciplina_id} onChange={(event) => alterar("disciplina_id", event.target.value)}><option value="">Componente curricular</option>{opcoes(listas.disciplinas, ["nome"])}</Select><Input value={formulario.periodo} onChange={(event) => alterar("periodo", event.target.value)} placeholder="Período (ex.: 1º bimestre)" /><Input value={formulario.tipo} onChange={(event) => alterar("tipo", event.target.value)} placeholder="Tipo de avaliação" /><Input type="date" value={formulario.data_avaliacao} onChange={(event) => alterar("data_avaliacao", event.target.value)} /><div className="grid grid-cols-2 gap-2"><Input type="number" min="0" value={formulario.valor_maximo} onChange={(event) => alterar("valor_maximo", event.target.value)} placeholder="Valor máximo" /><Input type="number" min="0" value={formulario.peso} onChange={(event) => alterar("peso", event.target.value)} placeholder="Peso" /></div></> : <><Select value={formulario.avaliacao_id} onChange={(event) => alterar("avaliacao_id", event.target.value)}><option value="">Avaliação</option>{opcoes(listas.avaliacoes, ["tipo", "periodo"])}</Select><Select value={formulario.matricula_id} onChange={(event) => alterar("matricula_id", event.target.value)}><option value="">Matrícula do aluno</option>{opcoes(listas.matriculas, ["numero_matricula", "aluno_id"])}</Select><Input type="number" min="0" value={formulario.valor} onChange={(event) => alterar("valor", event.target.value)} placeholder="Nota" /><Input value={formulario.conceito} onChange={(event) => alterar("conceito", event.target.value)} placeholder="Conceito (opcional)" /></>}<Button type="submit" disabled={carregando}>Salvar</Button></form>{mensagem ? <p className="mt-3 text-sm text-[var(--g3-muted)]">{mensagem}</p> : null}</CardContent></Card><Card><CardHeader><CardTitle>Registros salvos</CardTitle></CardHeader><CardContent className="space-y-2">{itens.map((item) => <div key={item.id} className="rounded-lg border border-[var(--g3-border)] bg-[var(--g3-card-soft)] p-3 text-sm">{recurso === "avaliacoes" ? `${texto(item, "tipo")} · ${texto(item, "periodo")}` : `${texto(item, "matricula_id")} · Nota ${texto(item, "valor")}`}</div>)}{!itens.length ? <p className="text-sm text-[var(--g3-muted)]">Nenhum registro encontrado.</p> : null}</CardContent></Card></div>;
}
