export type OcorrenciaCriancaPayload = {
  id?: string;
  dataPreenchimento: string;
  localViolencia?: string;
  localViolenciaOutro?: string;
  violenciaMotivadaPor?: string[];
  violenciaMotivadaOutro?: string;
  violenciaPraticadaPor?: string[];
  violenciaPraticadaOutro?: string;
  outrasViolacoes?: string[];
  vitimaNome: string;
  vitimaIdade: number | null;
  vitimaRacaCor?: string;
  vitimaIdentidadeGenero?: string;
  vitimaOrientacaoSexual?: string;
  vitimaOrientacaoOutro?: string;
  vitimaEscolaridade?: string;
  vitimaResponsavelTipo?: string;
  vitimaResponsavelNome?: string;
  vitimaTelefoneResponsavel?: string;
  vitimaEnderecoLogradouro?: string;
  vitimaEnderecoComplemento?: string;
  vitimaEnderecoBairro?: string;
  vitimaEnderecoMunicipio?: string;
  autorNome?: string;
  autorIdade?: number | null;
  autorNaoConsta?: boolean;
  autorParentesco?: string;
  autorParentescoGrau?: string;
  autorResponsavelTipo?: string;
  autorResponsavelNome?: string;
  autorResponsavelTelefone?: string;
  autorResponsavelNaoConsta?: boolean;
  autorEnderecoLogradouro?: string;
  autorEnderecoComplemento?: string;
  autorEnderecoBairro?: string;
  autorEnderecoMunicipio?: string;
  autorEnderecoNaoConsta?: boolean;
  tipificacaoViolencia?: string[];
  tipificacaoPsicologica?: string[];
  tipificacaoSexual?: string[];
  violenciaAutoprovocada?: string[];
  outroTipoViolenciaDescricao?: string;
  resumoViolencia: string;
  encaminharConselho?: boolean | null;
  encaminharMotivo?: string;
  dataEnvioConselho?: string;
  denunciaOrigem?: string[];
  denunciaOrigemOutro?: string;
  criadoEm?: string;
  atualizadoEm?: string;
};

export type OcorrenciaCriancaAnexoPayload = {
  id?: string;
  ocorrenciaId?: string;
  nomeArquivo: string;
  tipoMime: string;
  conteudoBase64: string;
  ordem: number;
  criadoEm?: string;
  atualizadoEm?: string;
};

