export type PlanoObjetivoEspecificoInput = {
  id?: string;
  descricao: string;
  resultadoEsperado?: string | null;
  metasVinculadas: string[];
};

export type PlanoMetaEtapaInput = {
  id?: string;
  nome: string;
  acaoExecutar?: string | null;
  descricaoDetalhada?: string | null;
  publicoAtendido?: string | null;
  quantidade?: number | null;
  unidade?: string | null;
  local?: string | null;
  dataInicio?: string | null;
  dataFim?: string | null;
  valorEstimado?: number | null;
  documentoComprobatorioEsperado?: string | null;
  responsavel?: string | null;
  situacao?: string | null;
};

export type PlanoMetaInput = {
  id?: string;
  numeroMeta: string;
  descricao: string;
  indicadorResultado?: string | null;
  unidadeMedida?: string | null;
  quantidadePrevista?: number | null;
  meioVerificacao?: string | null;
  dataInicio?: string | null;
  dataFim?: string | null;
  responsavel?: string | null;
  situacao?: string | null;
  etapas: PlanoMetaEtapaInput[];
};

export type PlanoAplicacaoRecursoInput = {
  id?: string;
  categoriaDespesa: string;
  item: string;
  descricao?: string | null;
  quantidade?: number | null;
  unidade?: string | null;
  valorUnitario?: number | null;
  valorTotal?: number | null;
  fonteRecurso?: string | null;
  metaNumero?: string | null;
  etapaNome?: string | null;
  naturezaDespesa?: string | null;
  observacao?: string | null;
};

export type PlanoDesembolsoInput = {
  id?: string;
  mesAno: string;
  valorPrevisto?: number | null;
  fonteRecurso?: string | null;
  metaNumero?: string | null;
  observacao?: string | null;
};

export type PlanoChecklistPrestacaoInput = {
  id?: string;
  descricao: string;
  obrigatorio?: boolean;
  concluido?: boolean;
};

export type PlanoTrabalhoInput = {
  id?: string;
  codigoInterno?: string | null;
  titulo: string;
  tipoParceria: string;
  orgaoParceiro: string;
  editalChamamento?: string | null;
  periodoInicio: string;
  periodoFim: string;
  status: string;
  responsavelTecnico: string;
  responsavelLegal: string;
  termoFomentoId?: string | null;
  numeroProcesso?: string | null;
  razaoSocial: string;
  nomeFantasia?: string | null;
  cnpj: string;
  cep?: string | null;
  logradouro?: string | null;
  numero?: string | null;
  complemento?: string | null;
  bairro?: string | null;
  cidade?: string | null;
  uf?: string | null;
  telefone?: string | null;
  email?: string | null;
  representanteLegal: string;
  representanteCpf: string;
  representanteCargo?: string | null;
  bancoNome?: string | null;
  bancoAgencia?: string | null;
  bancoConta?: string | null;
  bancoOperacao?: string | null;
  bancoPix?: string | null;
  bancoObservacao?: string | null;
  historicoOsc?: string | null;
  finalidadeInstitucional?: string | null;
  experienciaAnterior?: string | null;
  conselhosCertificacoes?: string | null;
  publicoAtendidoAtual?: string | null;
  capacidadeTecnicaOperacional?: string | null;
  descricaoObjeto: string;
  areaAtuacao: string;
  localExecucao: string;
  abrangenciaTerritorial?: string | null;
  publicoAlvo: string;
  quantidadeBeneficiarios?: number | null;
  criteriosSelecao?: string | null;
  problemaSocial: string;
  causasConsequencias?: string | null;
  dadosIndicadores?: string | null;
  capacidadeExecucao?: string | null;
  impactoEsperado?: string | null;
  objetivoGeral: string;
  objetivosEspecificos: PlanoObjetivoEspecificoInput[];
  metas: PlanoMetaInput[];
  aplicacaoRecursos: PlanoAplicacaoRecursoInput[];
  desembolso: PlanoDesembolsoInput[];
  formaAcompanhamento?: string | null;
  indicadoresMonitoramento?: string | null;
  periodicidadeMonitoramento?: string | null;
  responsavelColetaDados?: string | null;
  instrumentosMonitoramento: string[];
  resultadoEsperadoMonitoramento?: string | null;
  evidenciasObrigatorias?: string | null;
  periodicidadePrestacao?: string | null;
  dataLimitePrestacao?: string | null;
  documentosExigidos?: string | null;
  responsavelPrestacao?: string | null;
  observacoesPrestacao?: string | null;
  checklistPrestacao: PlanoChecklistPrestacaoInput[];
  localDeclaracao?: string | null;
  dataDeclaracao?: string | null;
  nomeRepresentanteDeclaracao?: string | null;
  cpfRepresentanteDeclaracao?: string | null;
  cargoRepresentanteDeclaracao?: string | null;
  declaracaoVeracidade?: boolean;
  aprovacaoInterna?: string | null;
  situacaoAprovacao?: string | null;
  observacaoAprovador?: string | null;
  arquivoFormato?: string | null;
};

export type PlanoTrabalhoRow = {
  id: bigint;
  codigo_interno: string;
  titulo: string;
  tipo_parceria: string | null;
  orgao_parceiro: string | null;
  edital_chamamento: string | null;
  periodo_inicio: Date | null;
  periodo_fim: Date | null;
  status: string;
  responsavel_tecnico: string | null;
  responsavel_legal: string | null;
  termo_fomento_id: bigint | null;
  numero_processo: string | null;
  razao_social: string | null;
  nome_fantasia: string | null;
  cnpj: string | null;
  cep: string | null;
  logradouro: string | null;
  numero: string | null;
  complemento: string | null;
  bairro: string | null;
  cidade: string | null;
  uf: string | null;
  telefone: string | null;
  email: string | null;
  representante_legal: string | null;
  representante_cpf: string | null;
  representante_cargo: string | null;
  banco_nome: string | null;
  banco_agencia: string | null;
  banco_conta: string | null;
  banco_operacao: string | null;
  banco_pix: string | null;
  banco_observacao: string | null;
  historico_osc: string | null;
  finalidade_institucional: string | null;
  experiencia_anterior: string | null;
  conselhos_certificacoes: string | null;
  publico_atendido_atual: string | null;
  capacidade_tecnica_operacional: string | null;
  descricao_objeto: string | null;
  area_atuacao: string | null;
  local_execucao: string | null;
  abrangencia_territorial: string | null;
  publico_alvo: string | null;
  quantidade_beneficiarios: number | null;
  criterios_selecao: string | null;
  problema_social: string | null;
  causas_consequencias: string | null;
  dados_indicadores: string | null;
  capacidade_execucao: string | null;
  impacto_esperado: string | null;
  objetivo_geral: string | null;
  forma_acompanhamento: string | null;
  indicadores_monitoramento: string | null;
  periodicidade_monitoramento: string | null;
  responsavel_coleta_dados: string | null;
  instrumentos_monitoramento: string | null;
  resultado_esperado_monitoramento: string | null;
  evidencias_obrigatorias: string | null;
  periodicidade_prestacao: string | null;
  data_limite_prestacao: Date | null;
  documentos_exigidos: string | null;
  responsavel_prestacao: string | null;
  observacoes_prestacao: string | null;
  local_declaracao: string | null;
  data_declaracao: Date | null;
  nome_representante_declaracao: string | null;
  cpf_representante_declaracao: string | null;
  cargo_representante_declaracao: string | null;
  declaracao_veracidade: boolean | null;
  aprovacao_interna: string | null;
  situacao_aprovacao: string | null;
  observacao_aprovador: string | null;
  arquivo_formato: string | null;
  criado_em: Date;
  atualizado_em: Date;
  termo_numero: string | null;
  termo_objeto: string | null;
  termo_responsavel_indicacao: string | null;
};

export type PlanoObjetivoEspecificoRow = {
  id: bigint;
  plano_trabalho_id: bigint;
  descricao: string;
  resultado_esperado: string | null;
  metas_vinculadas: string | null;
  ordem: number;
};

export type PlanoMetaRow = {
  id: bigint;
  plano_trabalho_id: bigint;
  numero_meta: string | null;
  descricao: string;
  indicador_resultado: string | null;
  unidade_medida: string | null;
  quantidade_prevista: number | null;
  meio_verificacao: string | null;
  data_inicio: Date | null;
  data_fim: Date | null;
  responsavel: string | null;
  situacao: string | null;
  ordem: number;
};

export type PlanoMetaEtapaRow = {
  id: bigint;
  meta_id: bigint;
  nome_etapa: string | null;
  acao_executar: string | null;
  descricao_detalhada: string | null;
  publico_atendido: string | null;
  quantidade: number | null;
  unidade: string | null;
  local_execucao: string | null;
  data_inicio: Date | null;
  data_fim: Date | null;
  valor_estimado: number | null;
  documento_comprobatorio: string | null;
  responsavel: string | null;
  situacao: string | null;
  ordem: number;
};

export type PlanoAplicacaoRecursoRow = {
  id: bigint;
  plano_trabalho_id: bigint;
  categoria_despesa: string;
  item: string;
  descricao: string | null;
  quantidade: number | null;
  unidade: string | null;
  valor_unitario: number | null;
  valor_total: number | null;
  fonte_recurso: string | null;
  meta_numero: string | null;
  etapa_nome: string | null;
  natureza_despesa: string | null;
  observacao: string | null;
  ordem: number;
};

export type PlanoDesembolsoRow = {
  id: bigint;
  plano_trabalho_id: bigint;
  mes_ano: string;
  valor_previsto: number | null;
  fonte_recurso: string | null;
  meta_numero: string | null;
  observacao: string | null;
  ordem: number;
};

export type PlanoChecklistPrestacaoRow = {
  id: bigint;
  plano_trabalho_id: bigint;
  descricao: string;
  obrigatorio: boolean;
  concluido: boolean;
  ordem: number;
};
