import { AppError } from "../../../shared/errors/app-error.js";
import { agendaSchema, alunoSchema, alunosAgrupadosFiltrosSchema, anoLetivoSchema, avaliacaoSchema, autorizacaoSchema, boletimSchema, buscaBeneficiarioSchema, calendarioSchema, chamadaRapidaSchema, configuracaoEducacionalSchema, criarVinculoAlunoSchema, desenvolvimentoInfantilSchema, diarioSchema, disciplinaSchema, documentoSchema, editarVinculoMatriculaSchema, enturmacaoSchema, etapaSchema, frequenciaSchema, gerarBoletimSchema, gerarHistoricoSchema, gradeCurricularSchema, historicoSchema, horarioSchema, listaEsperaSchema, matriculaSchema, notaSchema, ocorrenciaSchema, painelEducacionalFiltrosSchema, pendenciaEducacionalTipoSchema, pendenciasEducacionaisFiltrosSchema, planejamentoSchema, planoAulaSchema, profissionalVinculoSchema, recuperacaoSchema, recuperacaoSugestoesSchema, rematriculaLoteSchema, rematriculaSchema, resultadoFinalSchema, rotinaInfantilSchema, serieSchema, transferenciaMatriculaSchema, transferenciaSchema, turmaSchema } from "../educacional.schema.js";
import { EducacionalRepository } from "../repositories/educacional.repository.js";
import type { EducacionalActor, EducacionalRecurso } from "../educacional.types.js";

export class EducacionalService {
  private readonly repository = new EducacionalRepository();
  private readonly schemas = { "anos-letivos": anoLetivoSchema, etapas: etapaSchema, series: serieSchema, disciplinas: disciplinaSchema, turmas: turmaSchema, matriculas: matriculaSchema, enturmacoes: enturmacaoSchema, profissionais: profissionalVinculoSchema, "grade-curricular": gradeCurricularSchema, horarios: horarioSchema, diarios: diarioSchema, frequencias: frequenciaSchema, "planos-aula": planoAulaSchema, planejamentos: planejamentoSchema, avaliacoes: avaliacaoSchema, notas: notaSchema, boletins: boletimSchema, historicos: historicoSchema, ocorrencias: ocorrenciaSchema, agenda: agendaSchema, documentos: documentoSchema, "rotinas-infantis": rotinaInfantilSchema, "desenvolvimentos-infantis": desenvolvimentoInfantilSchema, transferencias: transferenciaSchema, autorizacoes: autorizacaoSchema, "lista-espera": listaEsperaSchema, recuperacoes: recuperacaoSchema, "resultados-finais": resultadoFinalSchema, calendario: calendarioSchema, configuracoes: configuracaoEducacionalSchema } as const;
  async resumo(rawFiltros: unknown, tenantId?: string) { return this.repository.resumo(painelEducacionalFiltrosSchema.parse(rawFiltros ?? {}), this.tenant(tenantId)); }
  async listarPendencias(rawTipo: string, rawFiltros: unknown, tenantId?: string) { return this.repository.listarPendencias(pendenciaEducacionalTipoSchema.parse(rawTipo), pendenciasEducacionaisFiltrosSchema.parse(rawFiltros ?? {}), this.tenant(tenantId)); }
  async listar(recurso: EducacionalRecurso, tenantId?: string) { return this.repository.listar(recurso, this.tenant(tenantId)); }
  async proximoNumeroMatricula(tenantId?: string) { return this.repository.proximoNumeroMatricula(this.tenant(tenantId)); }
  async buscarBeneficiarios(raw: unknown, tenantId?: string) { const input = buscaBeneficiarioSchema.parse(raw); return this.repository.buscarBeneficiarios(input.busca, this.tenant(tenantId)); }
  async listarUnidadesEnsino(tenantId?: string) { return this.repository.listarUnidadesEnsino(this.tenant(tenantId)); }
  async listarAlunosAgrupados(rawFiltros: unknown, tenantId?: string) { return this.repository.listarAlunosAgrupados(alunosAgrupadosFiltrosSchema.parse(rawFiltros ?? {}), this.tenant(tenantId)); }
  async vidaAcademicaAluno(rawId: string, tenantId?: string) { return this.repository.vidaAcademicaAluno(rawId, this.tenant(tenantId)); }
  async obterChamadaRapida(rawDiarioId: string, tenantId?: string) { return this.repository.obterChamadaRapida(rawDiarioId, this.tenant(tenantId)); }
  async salvarChamadaRapida(rawDiarioId: string, raw: unknown, tenantId?: string, actor: EducacionalActor = {}) { return this.repository.salvarChamadaRapida(rawDiarioId, chamadaRapidaSchema.parse(raw), this.tenant(tenantId), actor); }
  async gerarBoletimAutomatico(raw: unknown, tenantId?: string, actor: EducacionalActor = {}) { return this.repository.gerarBoletimAutomatico(gerarBoletimSchema.parse(raw), this.tenant(tenantId), actor); }
  async gerarHistoricoAutomatico(raw: unknown, tenantId?: string, actor: EducacionalActor = {}) { return this.repository.gerarHistoricoAutomatico(gerarHistoricoSchema.parse(raw), this.tenant(tenantId), actor); }
  async transferirMatricula(rawId: string, raw: unknown, tenantId?: string, actor: EducacionalActor = {}) { return this.repository.transferirMatricula(rawId, transferenciaMatriculaSchema.parse(raw), this.tenant(tenantId), actor); }
  async rematricular(rawId: string, raw: unknown, tenantId?: string, actor: EducacionalActor = {}) { return this.repository.rematricular(rawId, rematriculaSchema.parse(raw), this.tenant(tenantId), actor); }
  async rematricularLote(raw: unknown, tenantId?: string, actor: EducacionalActor = {}) { return this.repository.rematricularLote(rematriculaLoteSchema.parse(raw), this.tenant(tenantId), actor); }
  async sugerirRecuperacoes(raw: unknown, tenantId?: string) { return this.repository.sugerirRecuperacoes(recuperacaoSugestoesSchema.parse(raw ?? {}), this.tenant(tenantId)); }
  async listarHistoricoMatricula(rawId: string, tenantId?: string) { return this.repository.listarHistoricoMatricula(rawId, this.tenant(tenantId)); }
  async editarVinculoMatricula(rawId: string, raw: unknown, tenantId?: string, actor: EducacionalActor = {}) { return this.repository.editarVinculoMatricula(rawId, editarVinculoMatriculaSchema.parse(raw), this.tenant(tenantId), actor); }
  async criarVinculoAluno(rawId: string, raw: unknown, tenantId?: string, actor: EducacionalActor = {}) { return this.repository.criarVinculoAluno(rawId, criarVinculoAlunoSchema.parse(raw), this.tenant(tenantId), actor); }
  async vincularAluno(raw: unknown, tenantId?: string, actor: EducacionalActor = {}) { return this.repository.criarAluno(alunoSchema.parse(raw), this.tenant(tenantId), actor); }
  async salvar(recurso: EducacionalRecurso, rawId: string | undefined, raw: unknown, tenantId?: string, actor: EducacionalActor = {}) { const schema = this.schemas[recurso as keyof typeof this.schemas]; if (!schema) throw new AppError("Recurso educacional inválido.", 400); return this.repository.salvar(recurso, rawId, schema.parse(raw), this.tenant(tenantId), actor); }
  private tenant(value?: string) { if (!value?.trim()) throw new AppError("Tenant da sessão não identificado.", 401); return value.trim(); }
}
