ALTER TABLE documentos ADD COLUMN IF NOT EXISTS data_validade DATE;
ALTER TABLE documentos ADD COLUMN IF NOT EXISTS categoria VARCHAR(60);
ALTER TABLE documentos ADD COLUMN IF NOT EXISTS observacao TEXT;
ALTER TABLE documentos ADD COLUMN IF NOT EXISTS obrigatorio BOOLEAN;
ALTER TABLE documentos ADD COLUMN IF NOT EXISTS content_type VARCHAR(120);
ALTER TABLE documentos ADD COLUMN IF NOT EXISTS nome_arquivo VARCHAR(200);
ALTER TABLE documentos ADD COLUMN IF NOT EXISTS caminho_arquivo TEXT;
