ALTER TABLE prestacao_contas_aditivo
  ADD COLUMN IF NOT EXISTS prorrogacao_vigencia BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS valor_total_plano NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS parcela VARCHAR(60),
  ADD COLUMN IF NOT EXISTS valor_nova_parcela NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS corrigir_a_partir_parcela VARCHAR(60);
