import { useMemo, useState } from "react";
import { Activity, Archive, BarChart3, CalendarClock, FileText, Gavel, ListChecks, Plus, ShieldCheck, UsersRound, X } from "lucide-react";
import { AdminPageLayout, type AdminAction, type AdminTab } from "@/components/admin/admin-page-layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useAcaoEleicaoCipa, useDashboardCipa, useEleicoesCipa } from "@/features/cipa/use-cipa";
import { useUnidadesAssistenciais } from "@/features/unidades-assistenciais/use-unidades-assistenciais";
import { CipaImportadorEleitores } from "@/features/cipa/cipa-importador-eleitores";
import { CipaDocumentos } from "@/features/cipa/cipa-documentos";
import { CipaAuditoria } from "@/features/cipa/cipa-auditoria";
import { CipaGestaoOperacional } from "@/features/cipa/cipa-gestao-operacional";
import { CipaExtensaoVotacao } from "@/features/cipa/cipa-extensao-votacao";
import { CipaTransicoesEleicao } from "@/features/cipa/cipa-transicoes-eleicao";
import { CipaDivulgacaoEleicao } from "@/features/cipa/cipa-divulgacao-eleicao";
import { CipaResultadoEleicao } from "@/features/cipa/cipa-resultado-eleicao";
import { CipaCadastroColaborador } from "@/features/cipa/cipa-cadastro-colaborador";
import { CipaWizardEleicao } from "@/features/cipa/cipa-wizard-eleicao";
import { CipaEditarEleicao } from "@/features/cipa/cipa-editar-eleicao";
import { CipaSelecaoEleitores } from "@/features/cipa/cipa-selecao-eleitores";

type AbaCipa = "visao-geral" | "eleitores" | "candidatos" | "votacao" | "apuracao" | "documentos" | "auditoria" | "gestao";
const abas: AdminTab[] = [
  { id: "visao-geral", label: "Visão geral", icon: BarChart3 }, { id: "eleitores", label: "Eleitores", icon: UsersRound }, { id: "candidatos", label: "Candidatos", icon: Gavel }, { id: "votacao", label: "Votação", icon: Activity }, { id: "apuracao", label: "Apuração e resultado", icon: ListChecks }, { id: "documentos", label: "Documentos", icon: FileText }, { id: "auditoria", label: "Auditoria", icon: ShieldCheck }, { id: "gestao", label: "Gestão da CIPA", icon: Archive }
];
function statusLabel(status: string) { return status.replaceAll("_", " ").toLowerCase().replace(/^./u, (letra) => letra.toUpperCase()); }

export function CipaPage() {
  const eleicoesQuery = useEleicoesCipa(); const unidadesQuery = useUnidadesAssistenciais({}); const acaoMutation = useAcaoEleicaoCipa();
  const [abaAtiva, setAbaAtiva] = useState<AbaCipa>("visao-geral"); const [mostrarFormulario, setMostrarFormulario] = useState(false); const [eleicaoSelecionada, setEleicaoSelecionada] = useState<string>(); const [eleicaoEditando, setEleicaoEditando] = useState<string>();
  const eleicoes = eleicoesQuery.data?.eleicoes ?? []; const eleicao = eleicoes.find((item) => item.id === eleicaoSelecionada); const dashboardQuery = useDashboardCipa(eleicaoSelecionada);
  const unidadeNome = useMemo(() => new Map((unidadesQuery.data?.unidades ?? []).map((unidade) => [unidade.id_unidade ?? "", unidade.nome_fantasia])), [unidadesQuery.data]);
  function selecionarEleicao(id: string, aba: AbaCipa = "visao-geral") { setEleicaoSelecionada(id); setAbaAtiva(aba); }
  const acoes: AdminAction[] = [{ label: "Nova eleição", icon: Plus, onClick: () => { setMostrarFormulario(true); setEleicaoEditando(undefined); }, variant: "default" }];
  if (eleicao?.status === "CONFIGURACAO") acoes.push({ label: "Editar configuração", icon: FileText, onClick: () => setEleicaoEditando(eleicao.id), variant: "outline" });
  if (eleicao?.status === "INSCRICOES_ENCERRADAS") acoes.push({ label: "Publicar eleição", icon: ShieldCheck, onClick: () => void acaoMutation.mutateAsync({ acao: "publicar", eleicaoId: eleicao.id }), variant: "default", disabled: acaoMutation.isPending });
  if (eleicao?.status === "ELEICAO_PRONTA") {
    acoes.push({ label: "Gerar zerésima", icon: FileText, onClick: () => void acaoMutation.mutateAsync({ acao: "gerarZeresima", eleicaoId: eleicao.id }), variant: "outline", disabled: acaoMutation.isPending });
    acoes.push({ label: "Abrir votação", icon: Activity, onClick: () => void acaoMutation.mutateAsync({ acao: "abrirVotacao", eleicaoId: eleicao.id }), variant: "default", disabled: acaoMutation.isPending });
  }
  if (eleicao?.status === "VOTACAO_ABERTA") acoes.push({ label: "Encerrar votação", icon: X, onClick: () => { if (window.confirm("Após o encerramento, novos votos não poderão ser registrados. Deseja continuar?")) void acaoMutation.mutateAsync({ acao: "encerrarVotacao", eleicaoId: eleicao.id }); }, variant: "danger", disabled: acaoMutation.isPending });
  if (eleicao?.status === "VOTACAO_ENCERRADA") acoes.push({ label: "Apurar eleição", icon: ListChecks, onClick: () => void acaoMutation.mutateAsync({ acao: "apurar", eleicaoId: eleicao.id }), variant: "default", disabled: acaoMutation.isPending });
  if (eleicao && !["RESULTADO_PUBLICADO", "ENCERRADA", "CANCELADA"].includes(eleicao.status)) acoes.push({ label: "Cancelar eleição", icon: X, onClick: () => { const motivo = window.prompt("Informe o motivo do cancelamento (mínimo de 10 caracteres).", "Cancelamento solicitado pela organização"); if (motivo?.trim() && motivo.trim().length >= 10 && window.confirm("A eleição será cancelada e as sessões ativas serão revogadas. Deseja confirmar?")) void acaoMutation.mutateAsync({ acao: "cancelarEleicao", eleicaoId: eleicao.id, motivo: motivo.trim() }); }, variant: "ghost", disabled: acaoMutation.isPending });
  acoes.push({ label: "Fechar", icon: X, onClick: () => { window.location.href = "/dashboard/visao-geral"; }, variant: "outline" });
  const lista = eleicoesQuery.isLoading ? <p className="rounded-lg border border-[var(--g3-border)] p-6 text-center text-sm text-[var(--g3-muted)]">Carregando eleições...</p> : eleicoesQuery.isError ? <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800">Não foi possível carregar as eleições. Atualize a página e tente novamente.</p> : eleicoes.length === 0 ? <div className="rounded-lg border border-dashed border-[var(--g3-border)] p-10 text-center"><CalendarClock className="mx-auto h-9 w-9 text-[var(--g3-muted)]" /><p className="mt-3 font-medium">Nenhuma eleição cadastrada</p><p className="mt-1 text-sm text-[var(--g3-muted)]">Comece criando a eleição da CIPA para organizar o processo.</p><Button className="mt-4" onClick={() => setMostrarFormulario(true)}><Plus className="mr-2 h-4 w-4" />Criar primeira eleição</Button></div> : <div className="overflow-x-auto rounded-lg border border-[var(--g3-border)]"><table className="min-w-full text-left text-sm"><thead className="bg-[var(--g3-primary-soft)] text-[var(--g3-active)]"><tr><th className="px-3 py-2">Eleição</th><th className="px-3 py-2">Unidade</th><th className="px-3 py-2">Inscrições</th><th className="px-3 py-2">Votação</th><th className="px-3 py-2">Situação</th><th className="px-3 py-2 text-right">Ação</th></tr></thead><tbody>{eleicoes.map((item, index) => <tr key={item.id} className={`border-t border-[var(--g3-border)] ${index % 2 === 0 ? "bg-[var(--g3-card)]" : "bg-[var(--g3-primary-soft)]/35"}`}><td className="px-3 py-3"><button type="button" className="text-left font-medium text-[var(--g3-active)] hover:underline" onClick={() => selecionarEleicao(item.id)}>{item.nome}<span className="block text-xs font-normal text-[var(--g3-muted)]">Gestão {item.gestao}</span></button></td><td className="px-3 py-3">{unidadeNome.get(item.unidadeId) ?? "Estabelecimento"}</td><td className="whitespace-nowrap px-3 py-3">{item.inscricoesInicio.slice(0, 10)} a {item.inscricoesFim.slice(0, 10)}</td><td className="whitespace-nowrap px-3 py-3">{item.votacaoInicio.slice(0, 10)} a {item.votacaoFim.slice(0, 10)}</td><td className="px-3 py-3"><span className="rounded-full bg-[var(--g3-primary-soft)] px-2 py-1 text-xs font-medium">{statusLabel(item.status)}</span></td><td className="px-3 py-3 text-right"><Button size="sm" variant="outline" onClick={() => selecionarEleicao(item.id)}>Abrir</Button></td></tr>)}</tbody></table></div>;
  let conteudo: React.ReactNode = <section className="space-y-4"><p className="text-sm text-[var(--g3-muted)]">Selecione uma eleição na lista para acompanhar etapas, eleitores, candidatos, votação, apuração e documentos.</p>{lista}</section>;
  if (eleicaoSelecionada && eleicao) {
    conteudo = <div className="space-y-4"><div className="flex flex-col gap-3 rounded-lg border border-[var(--g3-border)] bg-[var(--g3-card-soft)] p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs text-[var(--g3-muted)]">Eleição selecionada</p><h2 className="font-semibold">{eleicao.nome}</h2><p className="text-sm text-[var(--g3-muted)]">Gestão {eleicao.gestao} · {unidadeNome.get(eleicao.unidadeId) ?? "Estabelecimento"}</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[var(--g3-primary-soft)] px-2.5 py-1 text-xs font-medium">{statusLabel(eleicao.status)}</span><Button size="sm" variant="outline" onClick={() => { setEleicaoSelecionada(undefined); setAbaAtiva("visao-geral"); }}>Trocar eleição</Button></div></div>{dashboardQuery.isLoading ? <p className="rounded-lg border border-[var(--g3-border)] p-4 text-sm text-[var(--g3-muted)]">Carregando indicadores da eleição...</p> : null}{dashboardQuery.isError ? <p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-800">Não foi possível carregar os indicadores desta eleição.</p> : null}
      {abaAtiva === "visao-geral" && dashboardQuery.data ? <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Eleitores aptos", dashboardQuery.data.eleitores.totalAptos], ["Já votaram", dashboardQuery.data.eleitores.votosRealizados], ["Ainda não votaram", dashboardQuery.data.eleitores.aindaNaoVotaram], ["Participação", `${dashboardQuery.data.eleitores.percentualParticipacao}%`]].map(([label, value]) => <div key={String(label)} className="rounded-lg border border-[var(--g3-border)] bg-[var(--g3-card-soft)] p-3"><p className="text-xs text-[var(--g3-muted)]">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</div><Card><CardHeader><CardTitle>Próxima etapa do processo</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-[var(--g3-muted)]">Execute somente as ações permitidas para a etapa atual.</p><CipaTransicoesEleicao eleicaoId={eleicao.id} status={eleicao.status} /></CardContent></Card><Card><CardHeader><CardTitle>Participação por grupo</CardTitle></CardHeader><CardContent className="grid gap-4 lg:grid-cols-3">{([['Unidade', dashboardQuery.data.participacao.porUnidade], ['Setor', dashboardQuery.data.participacao.porSetor], ['Turno', dashboardQuery.data.participacao.porTurno]] as const).map(([titulo, grupos]) => <section key={titulo}><h3 className="text-sm font-semibold">Por {titulo.toLowerCase()}</h3>{grupos.length ? <div className="mt-2 space-y-2">{grupos.map((grupo) => <div key={grupo.dimensao} className="rounded-lg border border-[var(--g3-border)] p-3"><div className="flex justify-between gap-2 text-sm"><span className="truncate" title={grupo.dimensao}>{grupo.dimensao}</span><strong>{grupo.percentualParticipacao}%</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[var(--g3-card-soft)]"><div className="h-full rounded-full bg-[var(--g3-active)]" style={{ width: `${Math.min(100, grupo.percentualParticipacao)}%` }} /></div><p className="mt-1 text-xs text-[var(--g3-muted)]">{grupo.votosRealizados} de {grupo.totalAptos} votaram</p></div>)}</div> : <p className="mt-2 text-sm text-[var(--g3-muted)]">Nenhum dado disponível.</p>}</section>)}</CardContent></Card></> : null}
      {abaAtiva === "eleitores" ? <><CipaSelecaoEleitores eleicaoId={eleicao.id} unidadeId={eleicao.unidadeId} permitir={["CONFIGURACAO", "INSCRICOES_ABERTAS"].includes(eleicao.status)} /><CipaImportadorEleitores eleicaoId={eleicao.id} onConcluido={() => { void dashboardQuery.refetch(); }} /><CipaCadastroColaborador unidadeId={eleicao.unidadeId} /></> : null}{abaAtiva === "candidatos" ? <CipaGestaoOperacional eleicaoId={eleicao.id} unidadeId={eleicao.unidadeId} permitir={["CONFIGURACAO", "INSCRICOES_ABERTAS", "INSCRICOES_ENCERRADAS"].includes(eleicao.status)} /> : null}{abaAtiva === "votacao" ? <><CipaDivulgacaoEleicao identificador={eleicao.identificadorPublico} nome={eleicao.nome} gestao={eleicao.gestao} /><CipaExtensaoVotacao eleicaoId={eleicao.id} aberta={eleicao.status === "VOTACAO_ABERTA"} onConcluido={() => { void eleicoesQuery.refetch(); void dashboardQuery.refetch(); }} /></> : null}{abaAtiva === "apuracao" ? <CipaResultadoEleicao eleicaoId={eleicao.id} status={eleicao.status} onPublicado={() => { void eleicoesQuery.refetch(); }} /> : null}{abaAtiva === "documentos" ? <CipaDocumentos eleicaoId={eleicao.id} /> : null}{abaAtiva === "auditoria" ? <CipaAuditoria eleicaoId={eleicao.id} /> : null}{abaAtiva === "gestao" ? <CipaGestaoOperacional eleicaoId={eleicao.id} /> : null}</div>;
  }
  if (mostrarFormulario) return <main className="min-h-screen bg-[var(--g3-bg)] p-4 md:p-6"><CipaWizardEleicao onConcluida={() => { setMostrarFormulario(false); void eleicoesQuery.refetch(); }} /></main>;
  if (eleicaoEditando) { const item = eleicoes.find((candidate) => candidate.id === eleicaoEditando); if (item) return <main className="min-h-screen bg-[var(--g3-bg)] p-4 md:p-6"><CipaEditarEleicao eleicao={item} onConcluida={() => { setEleicaoEditando(undefined); void eleicoesQuery.refetch(); }} /></main>; }
  return <AdminPageLayout tabs={abas} activeTab={abaAtiva} onChangeTab={(tabId) => setAbaAtiva(tabId as AbaCipa)} actions={acoes} sectionLabel="Recursos humanos · CIPA" pageTitle="Eleição CIPA" activeTitle={abas.find((item) => item.id === abaAtiva)?.label} activeIcon={abas.find((item) => item.id === abaAtiva)?.icon} codeBadge={eleicao ? `Gestão ${eleicao.gestao}` : "Visão geral"}>{acaoMutation.isError ? <p role="alert" className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-800">{acaoMutation.error instanceof Error ? acaoMutation.error.message : "Não foi possível concluir a ação."}</p> : null}{conteudo}</AdminPageLayout>;
}
