import { useEffect, useMemo, useState } from "react";
import { CalendarClock, Check, CheckCircle2, CreditCard, ExternalLink, Info, Save, ShieldCheck } from "lucide-react";
import { AdminPageLayout } from "@/components/admin/admin-page-layout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useAuth } from "@/hooks/use-auth";
import { useUnidadeAssistencialAtual } from "@/features/unidades-assistenciais/use-unidades-assistenciais";
import { licencaUsoService } from "@/services/licenca-uso.service";
import { comparativoModulos, ofertaPlanos, planoPorId, type OfertaPlano } from "@/pages/configuracoes/licenca-uso-oferta";
import type { LicencaUsoCiclo, LicencaUsoConfiguracao, LicencaUsoPlanoId, LicencaUsoResponse } from "@/types/licenca-uso";

const configuracaoInicial: LicencaUsoConfiguracao = {
  planoId: "profissional", cicloCobranca: "mensal", vigenciaInicialDias: 30, valorBaseMensal: 699,
  percentualDesconto: 0, valorCobranca: 699, valorImplantacao: 897, implantacaoIsenta: false,
  statusLicenca: "sem_vigencia", alertasEmailAtivos: true, diasAlertaEmail: [30, 15, 7, 1], emailsAlerta: [],
  pixAmbiente: "sandbox", pixExpiracaoMinutos: 1440, pixProvider: "mercado-pago", cartaoProvider: "mercado-pago",
  cartaoAmbiente: "sandbox", cartaoTentativasFalha: 2, boletoProvider: "mercado-pago", boletoAmbiente: "sandbox", boletoPrazoVencimentoDias: 5
};

function moeda(valor?: number) { return Number(valor ?? 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }
function dataPt(valor?: string) { return valor ? new Intl.DateTimeFormat("pt-BR").format(new Date(`${valor.slice(0, 10)}T00:00:00`)) : "Não definida"; }
function diasCiclo(ciclo: LicencaUsoCiclo) { return ciclo === "quadrienal" ? 1460 : ciclo === "trienal" ? 1095 : ciclo === "bienal" ? 730 : ciclo === "anual" ? 365 : ciclo === "semestral" ? 180 : 30; }
function mesesCiclo(ciclo: LicencaUsoCiclo) { return ciclo === "quadrienal" ? 48 : ciclo === "trienal" ? 36 : ciclo === "bienal" ? 24 : ciclo === "anual" ? 12 : ciclo === "semestral" ? 6 : 1; }
function descontoCiclo(ciclo: LicencaUsoCiclo) { return ciclo === "quadrienal" ? 50 : ciclo === "trienal" ? 40 : ciclo === "bienal" ? 30 : ciclo === "anual" ? 20 : ciclo === "semestral" ? 10 : 0; }
function implantacaoIsentaNoCiclo(ciclo: LicencaUsoCiclo) { return ciclo !== "mensal" && ciclo !== "semestral"; }
function nomeCiclo(ciclo: LicencaUsoCiclo) { return { mensal: "Mensal", semestral: "Semestral", anual: "Anual", bienal: "Bienal", trienal: "Trienal", quadrienal: "Quadrienal" }[ciclo]; }
function adicionarDias(data: string, dias: number) { const resultado = new Date(`${data}T00:00:00`); resultado.setDate(resultado.getDate() + dias - 1); return resultado.toISOString().slice(0, 10); }
function statusLabel(status: LicencaUsoConfiguracao["statusLicenca"]) { return { ativa: "Ativa", vence_hoje: "Vence hoje", vencida: "Vencida", sem_vigencia: "Sem vigência" }[status]; }
function calcular(plano: OfertaPlano, ciclo: LicencaUsoCiclo) { const desconto = descontoCiclo(ciclo); const valorCobranca = Number((plano.valorMensal * mesesCiclo(ciclo) * (1 - desconto / 100)).toFixed(2)); const implantacaoIsenta = implantacaoIsentaNoCiclo(ciclo); return { valorBaseMensal: plano.valorMensal, percentualDesconto: desconto, valorCobranca, valorImplantacao: implantacaoIsenta ? 0 : plano.implantacao, implantacaoIsenta }; }

function PlanoCard({ plano, selecionado, ciclo, onSelect }: { plano: OfertaPlano; selecionado: boolean; ciclo: LicencaUsoCiclo; onSelect: () => void }) {
  const desconto = descontoCiclo(ciclo);
  const mensal = Number((plano.valorMensal * (1 - desconto / 100)).toFixed(2));
  const totalCiclo = Number((mensal * mesesCiclo(ciclo)).toFixed(2));
  return <Card className={`relative flex h-full flex-col border-2 transition-all duration-200 ${selecionado ? "border-[var(--g3-active)] bg-emerald-100 shadow-2xl ring-2 ring-[var(--g3-active)]/35" : "border-[var(--g3-border)] bg-slate-100 shadow-md hover:-translate-y-0.5 hover:bg-white hover:shadow-lg"}`}>
    {plano.destaque ? <Badge className="absolute right-4 top-4 bg-[var(--g3-active)] text-white">{plano.destaque}</Badge> : null}
    <CardHeader className="pb-3 pr-28"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--g3-active)]">Plano G3N</p><CardTitle className="text-xl text-slate-950">{plano.nome}</CardTitle><p className="text-sm leading-5 text-slate-600">{plano.resumo}</p></CardHeader>
    <CardContent className="flex flex-1 flex-col gap-4"><div><p className="text-3xl font-bold text-slate-950">{moeda(mensal)}<span className="text-sm font-normal text-slate-500"> / mês</span></p><p className="mt-1 text-xs text-slate-500">{desconto > 0 ? `${desconto}% de desconto · cobrança do ciclo: ${moeda(totalCiclo)}${implantacaoIsentaNoCiclo(ciclo) ? " · implantação grátis" : ""}.` : `Implantação inicial de ${moeda(plano.implantacao)}.`}</p></div>
      <div className="rounded-xl border border-slate-200 bg-white p-3 text-sm"><p className="font-semibold text-slate-900">Indicado para</p><p className="mt-1 leading-5 text-slate-600">{plano.indicadoPara}</p></div>
      <div className="space-y-2"><p className="text-sm font-semibold text-slate-900">O que está incluído</p>{plano.funcionalidades.map((item) => <div key={item} className="flex items-start gap-2 text-sm text-slate-700"><Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />{item}</div>)}</div>
      <div className="mt-auto space-y-2 border-t border-slate-200 pt-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Regras do plano</p>{plano.limites.map((item) => <p key={item} className="text-xs leading-5 text-slate-500">• {item}</p>)}<Button type="button" onClick={onSelect} className="mt-2 h-10 w-full" variant={selecionado ? "default" : "outline"}>{selecionado ? <><CheckCircle2 className="mr-2 h-4 w-4" />Plano selecionado</> : plano.cta}</Button></div>
    </CardContent></Card>;
}

export function LicencaUsoPage() {
  const { usuario, atualizarPerfil } = useAuth();
  const { data: unidadeData } = useUnidadeAssistencialAtual();
  const [config, setConfig] = useState(configuracaoInicial);
  const [planoAtualId, setPlanoAtualId] = useState<LicencaUsoPlanoId>(configuracaoInicial.planoId);
  const [resumo, setResumo] = useState<LicencaUsoResponse["resumo"]>({ bloqueiaSistema: false });
  const [historico, setHistorico] = useState<LicencaUsoResponse["historico"]>({ pendentes: [], realizados: [] });
  const [carregando, setCarregando] = useState(true);
  const [salvando, setSalvando] = useState(false);
  const [gerando, setGerando] = useState(false);
  const [mensagem, setMensagem] = useState<{ tipo: "sucesso" | "erro"; texto: string }>();
  const [checkoutUrl, setCheckoutUrl] = useState("");

  useEffect(() => { let ativo = true; void licencaUsoService.obterConfiguracao().then((data) => { if (!ativo) return; setConfig((atual) => ({ ...atual, ...data.configuracao })); setPlanoAtualId(data.configuracao.planoId); setResumo(data.resumo); setHistorico(data.historico); }).catch((error) => ativo && setMensagem({ tipo: "erro", texto: error?.response?.data?.message ?? "Não foi possível carregar a licença." })).finally(() => ativo && setCarregando(false)); return () => { ativo = false; }; }, [usuario?.tenant_id]);
  const plano = useMemo(() => planoPorId(config.planoId), [config.planoId]);
  const planoAtual = useMemo(() => planoPorId(planoAtualId), [planoAtualId]);
  const ciclo = (["mensal", "semestral", "anual", "bienal", "trienal", "quadrienal"] as const).includes(config.cicloCobranca) ? config.cicloCobranca : "mensal";
  const inicio = config.dataInicioVigencia?.slice(0, 10) || new Date().toISOString().slice(0, 10);
  const fim = adicionarDias(inicio, diasCiclo(ciclo));
  const valores = calcular(plano, ciclo);
  const totalHoje = valores.valorCobranca + valores.valorImplantacao;
  const nomeInstituicao = unidadeData?.unidade?.nome_fantasia || config.instituicaoNome || "Instituição não identificada";
  function selecionar(id: LicencaUsoPlanoId) { const escolhido = planoPorId(id); setConfig((atual) => ({ ...atual, planoId: id, ...calcular(escolhido, ciclo) })); }
  function selecionarCiclo(novo: LicencaUsoCiclo) { setConfig((atual) => ({ ...atual, cicloCobranca: novo, vigenciaInicialDias: diasCiclo(novo), ...calcular(plano, novo) })); }
  function payload(): LicencaUsoConfiguracao { return { ...config, ...valores, cicloCobranca: ciclo, dataInicioVigencia: inicio, dataVencimento: fim, vigenciaInicialDias: diasCiclo(ciclo), instituicaoNome: nomeInstituicao, instituicaoCnpj: unidadeData?.unidade?.cnpj || config.instituicaoCnpj, emailsAlerta: config.emailsAlerta.length ? config.emailsAlerta : usuario?.email ? [usuario.email] : [] }; }
  async function salvar() { setSalvando(true); setMensagem(undefined); try { const data = await licencaUsoService.salvarConfiguracao(payload()); setConfig(data.configuracao); setPlanoAtualId(data.configuracao.planoId); setResumo(data.resumo); setHistorico(data.historico); await atualizarPerfil(); setMensagem({ tipo: "sucesso", texto: "Plano e condições de cobrança salvos com sucesso. O acesso aos módulos foi atualizado." }); } catch (error: any) { setMensagem({ tipo: "erro", texto: error?.response?.data?.message ?? "Não foi possível salvar o plano." }); } finally { setSalvando(false); } }
  async function gerarCheckout() { setGerando(true); setMensagem(undefined); try { await licencaUsoService.salvarConfiguracao(payload()); const data = await licencaUsoService.gerarCheckout(); setConfig(data.configuracao); setPlanoAtualId(data.configuracao.planoId); setResumo(data.resumo); setHistorico(data.historico); setCheckoutUrl(data.checkoutUrl ?? ""); await atualizarPerfil(); setMensagem({ tipo: "sucesso", texto: "Cobrança gerada. Confira a sequência abaixo e abra o checkout para concluir." }); } catch (error: any) { setMensagem({ tipo: "erro", texto: error?.response?.data?.message ?? "Não foi possível gerar a cobrança." }); } finally { setGerando(false); } }

  return <AdminPageLayout sectionLabel="Configurações gerais" pageTitle="Licença de uso" activeTitle="Licença de uso" actions={[{ label: salvando ? "Salvando..." : "Salvar plano", icon: Save, onClick: () => void salvar(), variant: "outline", disabled: carregando || salvando }, { label: gerando ? "Gerando cobrança..." : "Gerar cobrança", icon: CreditCard, onClick: () => void gerarCheckout(), variant: "default", disabled: carregando || salvando || gerando }]}>
    <div className="space-y-5 pb-8"><section className="rounded-2xl border border-[var(--g3-border)] bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--g3-active)]">Configuração comercial</p><h1 className="mt-1 text-2xl font-semibold text-slate-950">Escolha o plano da sua instituição</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Compare os quatro níveis, entenda exatamente o que será liberado e veja a cobrança antes de confirmar. O Enterprise libera todos os módulos.</p></div><div className="rounded-xl bg-[var(--g3-primary-soft)] px-4 py-3 text-sm text-slate-700"><p className="font-semibold">Instituição</p><p>{nomeInstituicao}</p><p className="text-xs">{config.instituicaoCnpj || unidadeData?.unidade?.cnpj || "CNPJ não informado"}</p></div></div></section>
      <section className="rounded-2xl border-2 border-[var(--g3-active)] bg-[var(--g3-primary-soft)] p-4 shadow-sm"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--g3-active)]">Plano atual da instituição</p><p className="mt-1 text-xl font-bold text-slate-950">{carregando ? "Carregando..." : planoAtual.nome}</p><p className="text-sm text-slate-600">Este é o plano vigente e que define os módulos liberados para sua instituição.</p></div><Badge className="w-fit bg-[var(--g3-active)] text-white">{statusLabel(config.statusLicenca)}</Badge></div></section>
      <section className="rounded-2xl border border-[var(--g3-border)] bg-white p-4"><div className="mb-3"><p className="text-sm font-semibold text-slate-900">Periodicidade da cobrança</p><p className="text-xs text-slate-500">Escolha o ciclo. Anual, bienal, trienal e quadrienal têm implantação gratuita e descontos progressivos.</p></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{(["mensal", "semestral", "anual", "bienal", "trienal", "quadrienal"] as const).map((item) => <button key={item} type="button" onClick={() => selecionarCiclo(item)} className={`rounded-xl border px-3 py-2 text-left text-sm ${ciclo === item ? "border-[var(--g3-active)] bg-[var(--g3-primary-soft)] font-semibold text-slate-950" : "border-slate-200 text-slate-600"}`}><span>{nomeCiclo(item)}</span><span className="mt-1 block text-xs font-normal">{descontoCiclo(item) ? `${descontoCiclo(item)}% de desconto` : "Sem desconto"}</span></button>)}</div></section>
      <section className="grid gap-4 xl:grid-cols-4">{ofertaPlanos.map((item) => <PlanoCard key={item.id} plano={item} selecionado={item.id === config.planoId} ciclo={ciclo} onSelect={() => selecionar(item.id)} />)}</section>
      <section className="rounded-2xl border border-[var(--g3-border)] bg-white p-4 shadow-sm"><div className="mb-4"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[var(--g3-active)]">Comparação dos módulos</p><h2 className="mt-1 text-xl font-semibold text-slate-950">Escolha a plataforma e adicione módulos quando precisar</h2><p className="mt-1 text-sm leading-6 text-slate-600">Os módulos marcados como “Adicional” podem ser contratados separadamente, sem obrigar sua instituição a fazer upgrade de plano.</p></div><div className="overflow-x-auto rounded-xl border border-slate-200"><table className="min-w-[760px] w-full text-sm"><thead className="bg-[var(--g3-primary-soft)]"><tr><th className="px-3 py-3 text-left font-semibold text-slate-900">Módulo ou recurso</th>{ofertaPlanos.map((item) => <th key={item.id} className={`px-3 py-3 text-center font-semibold ${config.planoId === item.id ? "bg-[var(--g3-active)] text-white" : "text-slate-900"}`}>{item.nome}</th>)}</tr></thead><tbody>{comparativoModulos.map((item, index) => <tr key={item.modulo} className={index % 2 ? "bg-slate-50/70" : "bg-white"}><td className="border-t border-slate-100 px-3 py-2.5 font-medium text-slate-700">{item.modulo}</td>{(["essencial", "profissional", "premium", "enterprise"] as const).map((planoId) => <td key={planoId} className={`border-t border-slate-100 px-3 py-2.5 text-center ${config.planoId === planoId ? "bg-[var(--g3-primary-soft)]/60 font-semibold text-[var(--g3-active)]" : "text-slate-600"}`}>{item[planoId]}</td>)}</tr>)}</tbody></table></div></section>
      <section className="grid gap-4 xl:grid-cols-[1.2fr_0.8fr]"><Card className="border-[var(--g3-border)]"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><ShieldCheck className="h-5 w-5 text-[var(--g3-active)]" />Plano escolhido: {plano.nome}</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-[var(--g3-primary-soft)] p-3"><p className="text-xs text-slate-500">Status</p><p className="mt-1 font-semibold">{statusLabel(config.statusLicenca)}</p></div><div className="rounded-xl bg-[var(--g3-primary-soft)] p-3"><p className="text-xs text-slate-500">Vigência</p><p className="mt-1 font-semibold">{dataPt(inicio)} a {dataPt(fim)}</p></div><div className="rounded-xl bg-[var(--g3-primary-soft)] p-3"><p className="text-xs text-slate-500">Desconto</p><p className="mt-1 font-semibold">{valores.percentualDesconto}%</p></div></div><p className="text-sm leading-6 text-slate-600">{plano.mensagemValor}</p><div className="flex items-start gap-2 rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm text-blue-900"><Info className="mt-0.5 h-4 w-4 shrink-0" /><span>Ao salvar, o plano passa a ser a referência de acesso da instituição. O bloqueio é aplicado no servidor e também refletido no menu.</span></div></CardContent></Card><Card className="border-[var(--g3-border)]"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><CalendarClock className="h-5 w-5 text-[var(--g3-active)]" />Sequência das cobranças</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><div className="flex justify-between gap-3"><span>Hoje — licença {plano.nome}</span><strong>{moeda(valores.valorCobranca)}</strong></div><div className="flex justify-between gap-3"><span>Hoje — implantação</span><strong>{valores.implantacaoIsenta ? "Grátis" : moeda(valores.valorImplantacao)}</strong></div><div className="border-t border-slate-200 pt-3"><div className="flex justify-between gap-3 font-semibold text-slate-950"><span>Total da contratação</span><span>{moeda(totalHoje)}</span></div><p className="mt-1 text-xs text-slate-500">Próxima cobrança após {mesesCiclo(ciclo) === 1 ? "1 mês" : `${mesesCiclo(ciclo)} meses`}, conforme a vigência.</p></div>{checkoutUrl ? <a href={checkoutUrl} target="_blank" rel="noreferrer"><Button type="button" className="mt-2 w-full"><ExternalLink className="mr-2 h-4 w-4" />Abrir checkout</Button></a> : null}</CardContent></Card></section>
      {mensagem ? <div className={`rounded-xl border px-4 py-3 text-sm ${mensagem.tipo === "erro" ? "border-red-300 bg-red-50 text-red-700" : "border-emerald-300 bg-emerald-50 text-emerald-700"}`}>{mensagem.texto}</div> : null}
      <details className="rounded-2xl border border-[var(--g3-border)] bg-white p-4"><summary className="cursor-pointer text-sm font-semibold text-slate-900">Ver histórico de cobranças</summary><div className="mt-4 grid gap-3 md:grid-cols-2">{[...historico.pendentes, ...historico.realizados].length ? [...historico.pendentes, ...historico.realizados].map((item) => <div key={item.id} className="rounded-xl border border-slate-200 p-3 text-sm"><div className="flex justify-between gap-3"><span>{item.descricao}</span><Badge>{item.status}</Badge></div><p className="mt-1 text-slate-600">{moeda(item.valorTotal)} · {item.criadoEm ? dataPt(item.criadoEm) : "Data não informada"}</p></div>) : <p className="text-sm text-slate-500">Nenhuma cobrança registrada.</p>}</div></details>
    </div>
  </AdminPageLayout>;
}
